project: 
  type: book
  output-dir: docs
  
toc: true

book:
  title: "Strength of Materials"
  page-navigation: true
  search: true
  sidebar:
    style: docked
    collapse-level: 0
  chapters: 
    - index.qmd
    - Chapter 1.qmd
    - Chapter 2.qmd
    - Chapter 3.qmd
    - Chapter 4.qmd
    - Chapter 5.qmd
    - Chapter 6.qmd
    - Chapter 7.qmd
    - Chapter 8.qmd
    - Chapter 9.qmd
    - Chapter 10.qmd
    - Chapter 11.qmd
    - Chapter 12.qmd
    - Chapter 13.qmd
    - Chapter 14.qmd
    - Chapter 15.qmd
  appendices:
    - Appendix A.qmd
    - Appendix B.qmd
    - Appendix C.qmd
    - Appendix D.qmd
    - Appendix E.qmd
    
format: 
  html: 
    fontsize: "10pt"
    theme:
      light:
      - flatly
      - include/light.scss
      dark:
      - darkly
      - include/dark.scss
    css: styles/custom.css
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
