project:
  type: book

book:
  title: "deformsbook"
  author: "Jake Grohs"
  date: "5/30/2023"
  search: true
  sidebar:
    style: docked
    background: light
  sharing: [facebook,twitter]
  chapters:
    - index.qmd
    - workoutproblem.qmd
    - workoutsolution.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt

editor: visual

