---
format: html
editor: visual
---

# Slope and Deflection Tables {#sec-slope-and-deflection-tables}

+-------------+------------------------------------+-------------------------------------------------+----------------------------------------------+
| Beam        | Slope                              | Max. Deflection                                 | Elastic Curve                                |
+=============+====================================+=================================================+==============================================+
|             | $\theta_{max}=- \frac{PL^2}{16EI}$ | $y_{max}=-\frac{PL^3}{48EI}$                    | $y=-\frac{Px}{48EI}\left(3L^2-4x^2\right)$   |
|             |                                    |                                                 |                                              |
|             |                                    |                                                 | Valid for x ≤ L/2                            |
+-------------+------------------------------------+-------------------------------------------------+----------------------------------------------+
|             | $\theta_A=-\frac{Pab(L+b}{6EIL}$   | $y_{max}=-\frac{Pb(L2-b2)^{3/2}}{9\sqrt{3}EIL}$ | $y=-\frac{Pbx}{6EIL}(L2-b2-x^2)$             |
|             |                                    |                                                 |                                              |
|             | $\theta_B=\frac{Pab(L+a)}{6EIL}$   | At $x=\sqrt{\frac{L^2-b^2}{3}}$                 | Valid for x \< a                             |
|             |                                    |                                                 |                                              |
|             |                                    |                                                 | At $x=a,~~~y=-\frac{Pa^2b^2}{3EIL}$          |
+-------------+------------------------------------+-------------------------------------------------+----------------------------------------------+
|             | $\theta_A=-\frac{ML}{6EI}$         | $y_{max}=-\frac{ML^2}{9\sqrt{3}EI}$             | $y=-\frac{Mx}{6EIL}(L^2-x^2)$                |
|             |                                    |                                                 |                                              |
|             | $\theta_B=\frac{ML}{3EI}$          | At $x=\frac{L}{\sqrt{3}}$                       |                                              |
+-------------+------------------------------------+-------------------------------------------------+----------------------------------------------+
|             | $\theta_{max}=-\frac{wL^3}{24EI}$  | $y_{max}=-\frac{5wL^4}{384EI}$                  | $y=-\frac{wx}{24EI}(x^3-2Lx^2+L^3)$          |
+-------------+------------------------------------+-------------------------------------------------+----------------------------------------------+
|             | $\theta_A =-\frac{3wL^3}{128EI}$   | $y_{max}=-\frac{wL^4}{152.37EI}$                | $y=-\frac{wx}{384EI}(16x^3-24Lx^2+9L^3)$     |
|             |                                    |                                                 |                                              |
|             | $\theta_B =\frac{7wL^3}{384EI}$    | At $x=0.4598L$                                  | Valid for $0\le x\le\frac{L}{2}$             |
|             |                                    |                                                 |                                              |
|             |                                    |                                                 | At $x=\frac{L}{2},~~~y=-\frac{5wL^4}{768EI}$ |
+-------------+------------------------------------+-------------------------------------------------+----------------------------------------------+
|             | $\theta_A =-\frac{7wL^3}{360EI}$   | $y_{max}=-\frac{wL^4}{153.37EI}$                | $y=-\frac{wx}{360EIL}(3x^4-10L^2x^2+7L^4)$   |
|             |                                    |                                                 |                                              |
|             | $\theta_B =\frac{wL^3}{45EI}$      | At $x=0.5193L$                                  |                                              |
+-------------+------------------------------------+-------------------------------------------------+----------------------------------------------+

: Slopes and Deflections of Simply Supported Beams

+-------------+-----------------------------------+--------------------------------+--------------------------------------------------+
| -Beam       | Slope                             | Max. Deflection                | Elastic Curve                                    |
+=============+===================================+================================+==================================================+
|             | $\theta_{max}=- \frac{PL^2}{2EI}$ | $y_{max}=-\frac{PL^3}{3EI}$    | $y = -\frac{Px^2}{6EI}(3L-x)$                    |
+-------------+-----------------------------------+--------------------------------+--------------------------------------------------+
|             | $\theta_{max}=- \frac{PL^2}{8EI}$ | $y_{max}=-\frac{5PL^3}{48EI}$  | $y=-\frac{Px^2}{12EI}(3L-2x)$                    |
|             |                                   |                                |                                                  |
|             |                                   |                                | Valid for $0\le x\le \frac{L}{2}$                |
|             |                                   |                                |                                                  |
|             |                                   |                                | $y=-\frac{PL^2}{48EI}(6x-L)$                     |
|             |                                   |                                |                                                  |
|             |                                   |                                | Valid for $\frac{L}{2}\le x \le L$               |
+-------------+-----------------------------------+--------------------------------+--------------------------------------------------+
|             | $\theta_{max}=- \frac{wL^3}{6EI}$ | $y_{max}=-\frac{wL^4}{8EI}$    | $y=-\frac{wx^2}{24EI}(x^2-4Lx+6L^2)$             |
+-------------+-----------------------------------+--------------------------------+--------------------------------------------------+
|             | $\theta_{max}=\frac{ML}{EI}$      | $y_{max}=\frac{ML^2}{2EI}$     | $y=\frac{Mx^2}{2EI}$                             |
+-------------+-----------------------------------+--------------------------------+--------------------------------------------------+
|             | $\theta_{max}=-\frac{wL^3}{48EI}$ | $y_{max}=-\frac{7wL^4}{384EI}$ | $y=-\frac{wx^2}{24EI}(x^2-2Lx+1.5L^2)$           |
|             |                                   |                                |                                                  |
|             |                                   |                                | Valid for $0\le x\le \frac{L}{2}$                |
|             |                                   |                                |                                                  |
|             |                                   |                                | $y=-\frac{wL^3}{384EI}(8x-L)$                    |
|             |                                   |                                |                                                  |
|             |                                   |                                | Valid for $\frac{L}{2}\le x\le L$                |
+-------------+-----------------------------------+--------------------------------+--------------------------------------------------+
|             | $\theta_{max}=-\frac{wL^3}{24EI}$ | $y_{max}=-\frac{wL^4}{30EI}$   | $y=-\frac{wx^2}{120EIL}(10L^3-10L^2x+5Lx^2-x^3)$ |
+-------------+-----------------------------------+--------------------------------+--------------------------------------------------+

: Slopes and Deflections of Cantilever Beams
