---
format: html
editor: visual
---

# Material Properties {#sec-material-properties}

## US Customary Units.

| Material                     | Specific Weight (lb/in.^3^) | Elastic Modulus (10^6^ psi) | Shear Modulus (10^6^ psi) | Poisson's Ratio | Coefficient of Thermal Expansion (10^-6^ /°F) | Yield Strength (Tens.) (ksi) | Yield Strength (Comp.) (ksi) | Ultimate Strength (Tens.) (ksi) | Ultimate Strength (Comp.) (ksi) |
|:-----------------------------|:---------------------------:|:---------------------------:|:-------------------------:|:---------------:|:---------------------------------------------:|:----------------------------:|:----------------------------:|:-------------------------------:|:-------------------------------:|
| Aluminum (**2014-T6**)       |            0.101            |            10.6             |            3.9            |      0.35       |                     12.8                      |              60              |              60              |               68                |               68                |
| Aluminum (**6061-T6**)       |            0.098            |            10.0             |            3.7            |      0.35       |                     13.1                      |              37              |              37              |               42                |               42                |
| Cast Iron (**Gray ASTM 20**) |            0.260            |            10.0             |            3.9            |      0.28       |                     6.70                      |              \-              |              \-              |               26                |               96                |
| Cast Iron (**Malleable**)    |            0.264            |            24.0             |            9.3            |      0.28       |                     6.70                      |              33              |              \-              |               40                |               83                |
| Copper (**C83400**)          |            0.316            |            14.6             |            5.4            |      0.35       |                     9.80                      |             11.4             |             11.4             |               35                |               35                |
| Copper (**C86100**)          |            0.319            |            15.2             |            5.6            |      0.34       |                     12.2                      |              50              |              50              |               95                |               95                |
| Steel (**A-36**)             |            0.284            |            29.0             |           11.2            |      0.32       |                     6.50                      |              36              |              36              |               58                |               58                |
| Steel (**A992**)             |            0.284            |            29.0             |           11.2            |      0.32       |                     6.50                      |              50              |              50              |               65                |               65                |
| Steel (**Stainless 304**)    |            0.284            |            28.0             |           11.0            |      0.27       |                     9.60                      |              30              |              30              |               75                |               75                |
| Titanium Alloy               |            0.160            |            17.4             |            6.4            |      0.36       |                     5.20                      |             134              |             134              |               145               |               145               |
| Concrete (**Low Strength**)  |            0.086            |            3.20             |            \-             |      0.15       |                      6.0                      |              \-              |              \-              |               \-                |               3.0               |
| Concrete (**High Strength**) |            0.086            |            4.20             |            \-             |      0.15       |                      6.0                      |              \-              |              \-              |               \-                |               6.0               |
| Douglas Fir                  |            0.017            |             1.9             |            \-             |      0.29       |                      \-                       |              \-              |              \-              |              15.0               |               7.2               |
| White Oak                    |            0.025            |             1.8             |            \-             |      0.31       |                      \-                       |              \-              |              \-              |               \-                |               7.4               |

: {.striped}

## SI Units

| Material                     | Density (kg/m^3^) | Elastic Modulus (GPa) | Shear Modulus (GPa) | Poisson's Ratio | Coefficient of Thermal Expansion (10^-6^ /°C) | Yield Strength (Tens.) (MPa) | Yield Strength (Comp.) (MPa) | Ultimate Strength (Tens.) (MPa) | Ultimate Strength (Comp.) (MPa) |
|:-----------------------------|:-----------------:|:---------------------:|:-------------------:|:---------------:|:---------------------------------------------:|:----------------------------:|:----------------------------:|:-------------------------------:|:-------------------------------:|
| Aluminum (**2014-T6**)       |       2790        |         73.1          |         27          |      0.35       |                      23                       |             414              |             414              |               469               |               469               |
| Aluminum (**6061-T6**)       |       2710        |         68.9          |         26          |      0.35       |                      24                       |             255              |             255              |               290               |               290               |
| Cast Iron (**Gray ASTM 20**) |       7190        |         67.0          |         27          |      0.28       |                      12                       |              \-              |              \-              |               179               |               669               |
| Cast Iron (**Malleable**)    |       7300        |          165          |         65          |      0.28       |                      12                       |             230              |              \-              |               345               |               620               |
| Copper (**C83400**)          |       8740        |          101          |         37          |      0.35       |                      18                       |              70              |              70              |               241               |               241               |
| Copper (**C86100**)          |       8830        |          103          |         38          |      0.34       |                      17                       |             345              |             345              |               655               |               655               |
| Steel (**A-36**)             |       7850        |          200          |         75          |      0.32       |                      12                       |             250              |             250              |               400               |               400               |
| Steel (**A992**)             |       7850        |          200          |         75          |      0.32       |                      12                       |             345              |             345              |               450               |               450               |
| Steel (**Stainless 304**)    |       7860        |          193          |         75          |      0.27       |                      17                       |             207              |             207              |               517               |               517               |
| Titanium Alloy               |       4430        |          120          |         44          |      0.36       |                      9.4                      |             924              |             924              |              1000               |              1000               |
| Concrete (**Low Strength**)  |       2380        |         22.1          |         \-          |      0.15       |                      11                       |              \-              |              \-              |               \-                |               20                |
| Concrete (**High Strength**) |       2370        |         29.0          |         \-          |      0.15       |                      11                       |              \-              |              \-              |               \-                |               30                |
| Douglas Fir                  |        470        |         13.1          |         \-          |      0.29       |                      \-                       |              \-              |              \-              |               100               |               48                |
| White Oak                    |        690        |         12.0          |         \-          |      0.31       |                      \-                       |              \-              |              \-              |               \-                |               51                |

: {.striped}
