---
format: html
editor: visual
---

# Units and Order of Magnitude {#sec-units-and-order-of-magnitude}

| Multiplication factor      | Prefix | Symbol | Example                                   |
|----------------------------|--------|--------|-------------------------------------------|
| 10^12^ = 1,000,000,000,000 | Tera   | T      | 1 Terawatt = 1 TW = 1 x 10^12^ watts      |
| 10^9^ = 1,000,000,000      | Giga   | G      | 1 Gigabyte = 1GB = 1 x 10^9^ bytes        |
| 10^6^ = 1,000,000          | Mega   | M      | 1 Megapascal = 1 MPa = 1 x 10^6^ Pascals  |
| 10^3^ = 1,000              | kilo   | k      | 1 kilonewton = 1 kN = 1 x 10^3^ Newtons   |
| 10^-3^ = 0.001             | milli  | m      | 1 millisecond = 1 ms = 1 x 10^-3^ seconds |
| 10^-6^ = 0.000001          | micro  | µ      | 1 micrometer = 1 µm = 1 x 10^-6^ meters   |
| 10^-9^ = 0.000000001       | nano   | n      | 1 nanovolt = 1 nV = 1 x 10^-9^ Volts      |
| 10^-12^ = 0.000000000001   | pico   | p      | 1 picoamp = 1 pA = 1 x 10^-12^ Amps       |

: Commonly used orders of magnitude

| Quantity                 | SI Unit (symbol)     | US Unit (symbol)                        | Conversion factor              |
|--------------------------|----------------------|-----------------------------------------|--------------------------------|
| 1^st^ Moment of Area (Q) | meters^3^ (m^3^)     | inches^3^ (in.^3^)                      | 1 in.^3^ = 1.639 x 10^-5^ m^3^ |
| 2^nd^ Moment of Area (I) | meters^4^ (m^4^)     | inches^4^ (in.^4^)                      | 1 in.^4^ = 4.162 x 10^-7^ m^4^ |
| Area (A)                 | meters^2^ (m^2^)     | inches^2^ (in.^2^)                      | 1 in.^2^ = 6.452 x 10^-4^ m^3^ |
| Force (F)                | Newton (N)           | Pound (lb)                              | 1 lb = 4.448 N                 |
| Length (L)               | Meter (m)            | Foot (ft) or Inch (in.)                 | 1 ft = 12 in. = 0.3048 m       |
| Moment of a force (M)    | Newton-meter (N·m)   | Pound-inch (lb·in.)                     | 1 lb·in. = 0.1130 N·m          |
| Power (P)                | Watt (W)             | horsepower (hp) or lb·ft/s              | 1 hp = 550 lb·ft/s = 1.356 W   |
| Pressure (P)             | Pascal (Pa)          | Pound per square inch (psi)             | 1 psi = 6895 Pa                |
| Strain (ε)               | Unitless             | Unitless                                | \-                             |
| Stress (σ)               | Pascal (Pa) = N/m^2^ | Pound per square inch (psi) = lb/in.^2^ | 1 psi = 6895 Pa                |
| Time (t)                 | Second (s)           | Second (s)                              | \-                             |
| Torque (T)               | Newton-meter (N·m)   | Pound-inch (lb·in.)                     | 1 lb·in. = 0.1130 N·m          |

: Commonly used units in this text
