---
format: html
editor: visual
---

# Stress {#sec-stress}

::: {.callout-note icon="false"}
## Learning Objectives

-   Use internal loads to calculate average normal stress
-   Use internal loads to calculate average shear stress
-   Use the loads between surfaces to calculate bearing stress
-   Calculate stresses on inclined planes
:::

## Introduction {style=".unnumbered"}

<details>

<summary>Click to expand</summary>

Having reviewed static equilibrium in Chapter 1, we now know how to find the internal loads in a body using equilibrium. When determining whether a body can resist the loads applied to it, the internal load is only part of the solution. The dimensions of the body and the inherent properties of the material it is made from are also important.

In this chapter we’ll explore the concept of stress, which can help us determine whether an object will physically break when subjected to a load. We’ll cover average normal stress (stress perpendicular to the cross-section) in Section 2.1 and average shear stress (stress parallel to the cross-section) in Section 2.2. We’ll then discuss bearing stress (the stress between two bodies in contact with each other) in Section 2.3 and finish with the average normal and shear stresses on an inclined cross-section in Section 2.4.

</details>

## Average Normal Stress

<details>

<summary>Click to expand</summary>

Average normal stress is defined as the internal normal force divided by the cross-sectional area of the body. It is given the Greek letter sigma (σ). Stress increases as the force increases or as the cross-sectional area decreases.

\[math\]

*where*

*𝜎 = Average normal stress \[Pa, psi\]*

*N = Internal normal force \[N, lb\]*

*A = Cross-sectional area \[m^2^, in^2^\]*

As such the SI units of stress are N/m^2^, more commonly referred to as the Pascal (Pa) where 1 Pa = 1 N/m^2^. The US customary units for stress are lb/in.2, commonly written as psi. Since stresses can get very large, it is common to use prefixes such as kilo (k) and mega (M) to represent 10^3^ and 10^6^ respectively. A stress of 15,000,000 Pa is written as 15 MPa. A stress of 35,000 psi is written as 35 ksi.

Normal stress occurs perpendicular to the cross-section and so is associated with either a pulling or pushing motion (Figure 2.1). Normal forces that pull on a cross-section are known as tensile forces and create a tensile normal stress. Normal forces that push on a cross-section are known as compressive forces and create a compressive normal stress. The normal stress calculated above is really an average normal stress as the force is distributed over the cross-section, but we generally simplify this to a concentrated force that creates the same normal stress at every point on the cross-section (Figure 2.2).

**Figure 2.1:** Forces pulling on a cross-section cause tension, while forces pushing on a cross-section cause compression. Both are very common. (Left) A crane cable during a lift experiences tension. (Right) The support columns under a bridge experience compression.

**Figure 2.2:** The internal load is equally distributed over the cross-sectional area, but may be represented as a single concentrated load acting at the center (N in this case). The stress is therefore an average normal stress.

The internal normal force in a body can be found through the method of equilibrium as learned in Statics. See Example 2.1 for a demonstration.

::: {.callout-note collapse="true" icon="false"}
## Example 2.1: Simple normal stress

The support column will be subjected to a compressive force F = 65 kips.

\[figure\]

1.  The diameter of the column is 4 inches. Determine the average normal stress in the column.

2.  The column is to be made of concrete with an allowable compressive stress of 4 ksi. For the same force F = 65 kips, determine the required diameter of the column so that the average normal stress does not exceed 4 ksi.

::: {.callout-note collapse="true" icon="false"}
## Solution

1.  Cut a cross-section through the column and draw a free body diagram. Although it is clear in this case that the internal load will be 65 kips, it is best to get in the habit of writing out equilibrium equations.

\[figure\]

\[math\]

The column has a circular cross-section of area \[math\]

The average normal stress can now be found from:

\[math\]

2.  Use the average normal stress equation again, but this time the stress is known to be 4 ksi. The loading has not changed so the internal normal force will still be 65 kips.

\[math\]

Since \[math\] we can find \[math\]

Then \[math\]

Note that this is the minimum required diameter to ensure the average normal stress does not exceed 4 ksi. If the diameter is any smaller than this, the stress will exceed the 4 ksi limit.
:::
:::

Sometimes the loading or cross-sectional area of the body will change, resulting in a change in stress. In these cases the stress can be calculated separately in each segment of the body by first finding the internal load in each segment and then dividing the internal load by the cross-sectional area of the respective segment. Different parts of the body may experience different stresses. Generally the highest stress is of most importance as that is the stress that typically determines whether the body will break. Because we do not know in advance where the largest stress is, however, it is typically necessary to calculate the stress at each different cross-section in order to determine the highest stress. See Example 2.2 for a demonstration.

::: {.callout-note collapse="true" icon="false"}
## Example 2.2: Normal stress with multiple loads/sections

Two hollow pipes are welded together as shown. Pipe (1) has an outer diameter of 70 mm and an inner diameter of 40 mm while pipe (2) has an outer diameter of 110 mm and an inner diameter of 60 mm. Forces are applied at the end of each pipe and at the weld, where F1 = 40 kN, F2 = 70 kN, and F3 = 30 kN. Determine the average normal stress in each pipe.

::: {.callout-note collapse="true" icon="false"}
## Solution

We can calculate average normal stress using \[math\] so we will need to find the area of each pipe and the normal force in each pipe. This can be done in any order. Starting with the areas:

\[math\]

The internal loads can be found by cutting a cross-section through each pipe, drawing a free body diagram, and writing an equilibrium equation.

\[math\]

Note that we may choose to draw the internal load in either tension or compression. The answer must be compared to the free body diagram. A positive answer from the equilibrium equation indicates that the direction drawn on the free body diagram was correct. Although both answers here were positive, it can be seen in the free body diagrams that N~1~ was drawn in compression and N~2~ was drawn in tension. These positive answers indicate that the drawings are correct. N~1~ is 40 kN in compression and N~2~ is 30 kN in tension.

Note also that it is acceptable to draw a free body diagram of either side of the cross-section. This will not change the result. Perhaps it would have been easier to draw the right-hand-side of section 2.

\[math\]

We again find that N~2~ is 30 kN in tension. You may always choose to draw either side of a cross-section. Make sure to include everything to that side of your cut, all the way to the end of the structure (e.g. do not stop at the weld).

Now that the areas and internal loads are known we can calculate the internal normal stresses.

\[math\]
:::
:::

::: {.callout-note icon="false"}
## Step-by-step: Needs title

1.  Use equilibrium equations to determine reaction loads at any supports.

2.  Cut a cross-section through the member at the point where you want to determine the internal normal stress, and draw a free body diagram of the member on either side of the cut. Be sure to include everything on the chosen side, including external loads, support reactions, and the internal normal force.

3.  Use equilibrium equations to determine the internal normal force (N) in the member.

4.  Determine average normal stress using \[math\]
:::

## Average Shear Stress

Average shear stress is defined as the internal shear force divided by the cross-sectional area of the body. While normal forces (and therefore normal stresses) occur when a body is under tension or compression, shear forces (and therefore shear stresses) occur when a force is tangentially applied parallel to the cross-section, resulting in a sliding motion (Figure 2.3).

**Figure 2.3:** (a) External loads F creating (b) an internal normal force (N) perpendicular to the cross-section. (c) External loads F1, F2, and F3 creating (d) an internal shear force (V) parallel to the cross-section. Note that for diagram (d) to be in equilibrium there would also need to be an internal bending moment. That has been omitted here for clarity.

Although the basic definition of average normal stress and average shear stress is the same (force divided by area) there are some differences. To quickly differentiate which stress we are talking about, shear stress is denoted by the Greek letter tau (τ).

\[math\]

   where            

τ = Average shear stress \[Pa, psi\]            

V = Internal sheal force \[N, lb\]            

A = Cross-sectional area \[m^2^, in^2^\]

Like normal force, internal shear force can be found by cutting a cross-section through the body, drawing a free body diagram, and applying equilibrium equations. See Example 2.3 for a demonstration.

::: {.callout-note collapse="true" icon="false"}
## Example 2.3: Simple shear stress

A bridge spans a gap of L = 150 ft. The roadway may be considered simply supported and has a rectangular cross-section of base b = 10 in. and height h = 6 in. It is subjected to a uniform distributed load of w = 200 lb/ft. Determine the magnitude of the average shear stress in the cross-section at x = 30 ft and x = 80 ft.

::: {.callout-note collapse="true" icon="false"}
## Solution

Average shear stress can be calculated from \[math\]. The cross-sectional area is \[math\]

The reactions at the support can be found by converting the distributed load into a statically equivalent concentrated load. This load will be equal to \[math\] and will be located at the center of the bridge. Since the loading is symmetric, each support will support half of this load, or 15000 lb each.

The internal shear force can be found by cutting a cross-section through the point of interest, drawing a free body diagram, and applying equilibrium equations. Remember to include the internal loads V and M, and to again convert the distributed load into a statically equivalent concentrated load over this portion of the bridge.

At x = 30 ft:

\[math\]

Note that an internal bending moment is also necessary in order to maintain equilibrium. We could find M by summing moments about any point, but it is not needed in order to solve this problem.

The shear stress can now be calculated.

\[math\]

At x = 80 ft:

\[math\]

Note that the negative sign here simply indicates that V is acting in the opposite direction of that drawn in the free body diagram. It can be discarded here as we are calculating the magnitude of the average shear stress at each point.

\[math\]
:::
:::

Shear stresses are common in both members of a structure and also in the fasteners between members. Depending on how these connections are formed we may see multiple shear planes. It is very important to correctly identify the internal force in the body. Figure 2.4 demonstrates the difference between single and double shear configurations for a pinned joint and the effects on internal shear force. See Example 2.4 for an example where double shear occurs.

**Figure 2.4:** Pins experiencing (a) single shear and (b) double shear.

::: {.callout-note collapse="true" icon="false"}
## Example 2.4: Shear stress with double shear

A pin made of a tin alloy with an allowable shear stress of 3 ksi is used to connect a footrest to the frame of a motorcycle. When in motion, the footrest supports a load of 200 lb which is transferred to the pin. Determine the required diameter of the pin such that the stress will not exceed 5 ksi.

::: {.callout-note collapse="true" icon="false"}
## Solution

Average shear stress can be calculated from \[math\]. Rearrange this equation to \[math\]. Start with a free body diagram of the pin in order to determine the internal shear force.

From the diagram it should be apparent that the pin is in double shear and the maximum internal shear force in the pin is 100 lb. Thus the required cross-sectional area \[math\].

Since \[math\] the required diameter is \[math\]
:::
:::

::: {.callout-note icon="false"}
## Step-by-step: Needs title

1.  Use equilibrium equations to determine reaction loads at any supports.

2.  Cut a cross-section through the member at the point where you want to determine the internal shear stress, and draw a free body diagram of the member on either side of the cut. Be sure to include everything on the chosen side, including external loads, support reactions, and the internal shear force.

3.  Use equilibrium equations to determine the internal shear force (V) in the member.

4.  Determine average normal stress using \[math\]
:::

## Bearing Stress

Bearing stress is similar to normal stress, except that it occurs at the contact area between two bodies instead of within a single body. Bearing stress is calculated with the average normal stress equation, where the cross-sectional area is the contact area between the two bodies (Figure 2.5).

**Figure 2.5:** Circular column sitting upon a rectangular foundation. Contact areas between a circular and rectangular surface, and between two rectangular surfaces are shown.

One common situation is contact between two curved edges, such as the bolt in Figure 2.6. In this situation it is common to use the projected contact area between the curved surfaces, which forms a rectangle of base d and height t. This greatly simplifies the calculation, but again represents an average value for the contact or bearing stress.

**Figure 2.6:** When calculating the bearing stress between curved surfaces, project a rectangle of area A = d\*t.

::: {.callout-note icon="false"}
## Step-by-step:

1.  Use equilibrium equations to determine reaction loads at any supports.

2.  Determine the contact area between the two components (A).

3.  Use equilibrium equations to determine the normal force (N) between the two components.

4.  Determine average bearing stress using \[math\]
:::

## Stress on an Inclined Plane

We have so far been cutting cross-sections perpendicular to the external force, or parallel to it. However, there is no rule that says we have to do this. It is perfectly acceptable to cut cross-sections at an angle and there are many situations where it may make sense to do so (Figure 2.7)

**Figure 2.7:** (a) External loads, F, will create (b) an internal normal force, N, when a cross-section is cut vertically. (c) If the cross-section is cut along an inclined plane the internal force, P, will not be a normal force or shear force. (d) The internal force should be broken into normal (N) and shear (V) components that are perpendicular and parallel to the plane respectively.

In this scenario the internal load must still be equal and opposite to the external load in order to maintain equilibrium but, because we cut the cross-section at an angle, this internal load is neither parallel nor perpendicular to the cross-section. Therefore it is not entirely a normal force or a shear force. However, the internal force may be broken into components that are perpendicular and parallel to the cross-section.

\[math\]

The area used to calculate the average normal and shear stresses must be the area of the inclined plane (Figure 2.8). By setting up a right-angled triangle it should be apparent that the area of the plane, A~p~, can be found from:

\[math\]

We can calculate average normal stress from \[math\]

We can calculate average shear stress from \[math\]

Note these equations assume the angle (θ) is measured from the axis perpendicular to area A. For a horizontal beam, area A is in the vertical plane so angle θ is measured from the horizontal axis.

**Figure 2.8:** When calculating the stresses on an inclined plane, it is important to use the area of the plane, A~p~, rather than the area of the cross-sectional plane, A.

Even if the external load remains constant, we can obtain different values for the internal normal and shear forces (and therefore different values for the stresses) by changing the angle at which we cut the cross-section. We’ll explore the implications of this further in Chapter 13.

::: {.callout-note collapse="true" icon="false"}
## Example 2.5: Inclined plane

A beam is formed of two structural wooden members that are glued together along an inclined plane at angle θ = 40° and subjected to a tensile force of F = 30 kN. The height of the beam is 50 mm and its thickness is 20 mm. Determine the normal and shear stresses created along the inclined plane.

\[figure\]

::: {.callout-note collapse="true" icon="false"}
## Solution

Begin by cutting a cross-section along the inclined plane and drawing a free body diagram. Remember to include the internal normal and shear forces perpendicular and parallel to the cross-section.

\[figure\]

Use equilibrium equations to determine the internal forces. It will be easiest to define axes parallel and perpendicular to the inclined plane.

\[math\]

With F = 30 kN and θ = 40°, these can be solved for N = 19.3 kN and V = 23.0 kN.

Next, determine the cross-sectional area of the inclined plane.

\[math\]

With A = 0.05 m x 0.02 m = 0.001 m2 and θ = 40°, Ap = 0.00156 m2.

Finally, determine the average normal stress and the average shear stress.

\[math\]
:::
:::

::: {.callout-note icon="false"}
## Step-by-step:

1.  Use equilibrium equations to determine reaction loads at any supports.

2.  Cut a cross-section along the inclined plane and determine the angle (θ) of the plane with respect to the axis perpendicular to cross-sectional area A.

3.  Use equilibrium equations to determine the internal load (F).

4.  Determine average normal stress using \[math\]

5.  Determine average shear stress using \[math\]
:::

## Summary

::: {.callout-note icon="false"}
## Key takeaways

Objects under load will experience stress. It is the stress level (rather than just the load by itself) that determines whether an object will break under load. We can calculate the average normal stress and average shear stress acting on a body, though a complete understanding of the stress field within a complex object often requires more advanced concepts.

Stress depends on the internal load in the body, the cross-sectional area, and the orientation of the plane. Normal stress occurs when there is an internal normal force and may be tensile or compressive. Shear stress occurs when there is an internal shear force. Members may commonly experience multiple shear planes.

If there are multiple loads acting on a body, or if the body has multiple cross-sectional areas at different points, different parts of the body may experience different stresses. In such cases, we may calculate the stress in each part of the body by finding the internal load and cross-sectional area in that part of the body. In this chapter we have discussed average stress. In subsequent chapters further details on stress distributions will be discussed.

Bearing stress is similar to normal stress, but occurs between two bodies.

We may calculate stresses along inclined planes by cutting a cross-section at an angle. Determining the stresses at different angles will be important later in our studies.
:::

::: {.callout-note icon="false"}
## Key equations

Average normal stress:

\[math\]

Average shear stress:

\[math\]

Bearing stress:

\[math\]

Average stresses on an inclined plane:

\[math\]
:::
