---
format: html
editor: visual
---

## Introduction {.unnumbered}

### What Is Mechanics?

Mechanics can be broadly categorized in three parts, of which this text covers one. **Statics** explores the effects of *external loads* applied to *rigid bodies* in *equilibrium*. **Dynamics** explores the effects of *external loads* applied to *rigid bodies* that are not in *equilibrium.* In ***Strength of Materials***, we explore the mechanics of deformable bodies, learning about the effects of both *external* and *internal loads* on *nonrigid bodies* in *equilibrium*.

Since bodies in this text are in equilibrium, many of the principles from statics apply. However, because these bodies are nonrigid, a much deeper analysis is required. Objects discussed in this text will deform. When loads are applied, they will change their shapes. They will elongate and bend and twist and, if we're not careful, may even break. Real objects are deformable, and engineers must take great care to ensure that their designs do not break or deform so much that they are unfit for purpose.

Have you ever wondered why civil engineers tend to use certain materials for bridges and buildings, while automotive engineers use an entirely different set of materials in cars? Meanwhile, aerospace engineers don't make rockets out of the same materials that biomedical engineers use for prosthetics. There are many material properties that determine applications that a given material may, or may not, be suitable for. Two fundamental concepts explored in this text are stress, which helps us determine whether an object will break under a given load, and strain, which relates to the object's deformation.

Depending on how external loads are applied, there are a variety of potential internal loads on our object. You are likely already familiar with these loads and their effects, even if you haven't explicitly thought about them.

-   **Axial forces** push or pull on a body. They cause elongation and compression. For example, imagine pulling on the ends of an elastic band. The band will stretch significantly. Objects may be pulled apart or crushed by this load. Imagine doing the same with a piece of chalk. There will be a small amount of deformation and the chalk will break.

-   **Bending moments** act to bend an object. Imagine propping a long piece of plywood up on two supports and standing in the middle. The wood will bend. If you jump and land hard enough, it may even break.

-   **Shear forces** are created when one body (or part of a body) slides relative to another. They commonly occur in conjunction with bending moments.

-   **Torsional moments** act to twist an object. Imagine holding the ends of a cable and rotating your wrists so that the cable twists around itself along its length. You will see the cable rotate through ever larger angles. Twist it too far and it will break.

This text explores the effects of these loads and will expand your understanding of these effects. It aims to describe these effects in a conceptual way, building on your existing understanding. Once these effects are understood conceptually, you'll learn how to calculate the exact amount of deformation and the exact size of the stress created as well as how to make sure that your designs stay within appropriate limits.

### Scope

This book is intended for use in introductory undergraduate mechanics of materials courses. Such courses are typically early in the curriculum, following statics and generally serving as a prerequisite to more advanced solid mechanics courses. As such, this book begins with a review of static equilibrium before introducing the concepts of stress and strain and the relationship between them, along with pertinent material properties. The following chapters explore stress and deformation under four loading conditions: axial loads, torsional moments, bending moments, and transverse loads. Methods for determining internal loads and relevant geometric properties are included.

Once stress and deformation under each loading condition are well understood, stress transformation is introduced. This is followed by a brief discussion of thin-walled pressure vessels before tying together many of the previous chapters in an exploration of combined loading scenarios. Finally, column buckling is examined as a potential failure mode.

### Target Audience

This textbook is intended for a wide range of engineering undergraduate students. The content is fundamental to several disciplines, including mechanical, civil, aerospace, and materials engineering. This text covers fundamental skills and concepts that students will rely on throughout their studies and their careers.

### Motivation

Existing textbooks covering this material are expensive for students and tightly controlled by their publishers. There are some scattered open resources to aid student learning, but this book provides a cohesive resource that covers a typical mechanics of materials course from start to finish. It is free to use, and instructors are free to adapt the book to their specific needs.

Our experience teaching this class is that students report rarely using their textbooks for anything beyond assigned homework problems. They often find the books dense and impenetrable and struggle in a course they perceive to contain many disparate topics. This text attempts to more clearly demonstrate the links between the various topics and help students realize that the course is really about the application of just a handful of concepts. In our experience, students who make these connections find the course much easier than those who don’t.

### Approach and Features

**A cohesive narrative across the book**. Each chapter begins with a paragraph explaining the purpose of the chapter and where it ties into the course. Relevant topics are then introduced with a reason for studying the topic, the underlying concepts are explored, and any relevant equations are provided with derivations where appropriate. Applications are demonstrated, and each chapter ends with a summary of the key takeaways and equations.

**Conceptual understanding first, followed by numerical problem solving**. Conceptual understanding is key to performing well not only in this course but also in subsequent courses and as an engineer. Topics are approached conceptually first, with realistic applications used as a tool to aid understanding. Extensive worked examples are used liberally to demonstrate application of the concepts to numerical problems. Worked examples include thorough explanations of what is being done to solve the problem and why.

**Diverse problem sets**. Practice makes perfect, and so it is vital that students have diverse and extensive problem sets to practice applying the material. A large number of problems are included with each chapter, ranging from traditional idealized problems to problems with real-world applications in a variety of engineering disciplines.

This course is often high-enrollment and instructors often teach multiple sections. With so many students, grading can be a challenge. Consequently, the problem sets in this book have been recreated online with an interface that can intelligently provide feedback to students. Timely feedback is so important to student understanding. More than just letting students know whether they got the right or wrong numerical answer, this feedback helps students identify and understand their mistakes.

**Color coding and collapsible content**. Each chapter begins with defined learning objectives. Lists of learning objectives are blue.

::: {.callout-note icon="false"}
## Learning Objectives

-   These blocks include leaning objectives for the chapter.

-   These are short statements describing what you should be able to achieve upon completing the chapter.
:::

Chapters are organized into short sections. When opening a chapter, the learning objectives and Introduction section will be visible, while the other chapter sections are collapsed. Each section is independently expandable to aid navigation. Sections include explanatory text and worked examples for practice. Worked examples are green. They include an initial expandable box containing the problem statement, and a separately expandable box containing the worked solution. Students may choose to access the solution at any time or may attempt the problem themselves before checking their solution against the worked example.

::: {.callout-tip collapse="true" icon="false"}
## Worked Example - This block is expandable

Here you'll find the problem statement and any relevant diagrams. The solution is hidden behind another block, allowing you to attempt the problem before viewing the solution, if desired.
:::

::: {.callout-tip collapse="true" icon="false"}
## Solution - This block is expandable

Here you'll find a full worked solution and final answer. The solution includes the final answer, all calculations, and an explanation of why each calculation is used.
:::

Most sections end with step-by-step instructions for solving problems related to that section. These are orange.

::: {.callout-warning icon="false"}
## Step-by-Step

1.  These boxes contain a numbered list of steps for approaching problems related to each section.

2.  These are helpful for reminding yourself how to approach problems.

3.  However, they lack the conceptual detail that is vital for understanding.
:::

Each chapter ends with a summary section containing key takeaways and key equations. Like the learning objectives, these are blue.

### Organization

This book begins with a review of static equilibrium for single members, trusses, and frames. Internal loads are then introduced.

Chapters 2 and 3 contain an overview of stress and strain, and Chapter 4 discusses the relationship between them. Important material properties such as yield stress, elastic modulus, and Poisson’s ratio are introduced, and Hooke’s law is applied in one and three dimensions. Thermal strain and factor of safety are also introduced here.

The following chapters cover stress and strain under various loading conditions. Chapter 5 covers axial stress, deformation, stress concentrations, and thermal deformation. Statically indeterminate problems are also introduced here and repeated several times throughout the text. Chapter 6 covers torsional stress, deformation, power transmission, and statically indeterminate problems again.

Before considering bending and shear loads, Chapter 7 reviews several methods for determining internal shear force and bending moment. Equilibrium methods, integration, and graphical methods are all described. Chapter 8 provides methods for determining geometric properties such as centroid and second moment of area. Chapters 9 and 10 then discuss bending stress and shear stress respectively. These equations necessarily rely on the material from Chapters 7 and 8. Chapter 11 then covers beam deflection by integration and by superposition, as well as the application of these methods to statically indeterminate problems.

Once students have a thorough understanding of the effects of these four different loads, stress transformation is introduced in Chapter 12. General stress transformation in 2D and determination of the principal stresses and maximum in-plane shear stress are discussed first. Mohr’s circle is then discussed as an alternative method and is expanded to cover out-of-plane shear stress.

Chapter 13 covers spherical and cylindrical thin-walled pressure vessels. Chapter 14 brings much of the earlier content together and introduces combined load problems. Eccentric axial loads are discussed first as a specific subset of combined load problems. The principles are then expanded to general combined load problems that include any of or all the previously discussed loads.

Finally, buckling of columns is considered as a potential failure mode. The course wraps up with a reminder that both stress and deformation must be considered and that anything students work on must satisfactorily resist both.

## Acknowledgments

The creation of this Open Educational Resource (OER) was supported by a [VIVA Open Grant](https://vivalib.org/va/open/grants). The Virginia General Assembly has provided funds to support the VIVA Open Grant Program through [VIVA](https://vivalib.org/viva/homepage), Virginia’s Academic Library Consortium, a program of the State Council of Higher Education. The VIVA Open Grant Program aims to improve academic success for Virginia students by eliminating the costs of textbooks and other course materials and providing day one access to materials while also empowering faculty to create resources tailored to individual course needs and pedagogical goals. The program provides financial and publishing support services without content oversight.

The authors would like to thank Shaghayegh Bagheri, Jacob Moore, Joao Soares, and a fourth reviewer who preferred to remain anonymous. Their time, effort, and thoughtful feedback as peer reviewers made a meaningful impact on the quality of this textbook.

Thank you to Sanjay Vuttarapally, Grant Helm, and Alyssa Micheli for their feedback as student reviewers. In addition, the authors thank anonymous student focus group participants, and Olivia Ryan, Anita Walz, Benjamin Chaback, and Cassie Wallwey who planned and led student focus groups.

Thank you to Ben (Doyoon) Lee and Beyza Nur Guler for writing alternative text for this book.

Many of the figures in the book and question bank are adapted from Kurt Gramoll’s original work. Thank you, Kirk, for allowing us to adapt your work.

## Available Formats

### Book

*Strength of Materials* is an open textbook. You are welcome to freely use, adapt, and share this book with attribution according to the Creative Commons Attribution NonCommercial ShareAlike 4.0 ([CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)) license. This license allows customization and redistribution that is "not primarily intended for or directed toward commercial advantage or monetary compensation.” If you remix, transform, or build on the material, you must distribute your contributions under the same license as the original. All figures in this book are licensed under Creative Commons licenses or used under fair use. Please see the end-of-chapter references for license information for each figure before reuse.

If you are interested in making your own version of this book, check out the [book’s license](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en) and information on [recommended practices for attribution](https://wiki.creativecommons.org/wiki/Recommended_practices_for_attribution).

### Question Bank

This book has an accompanying set of [practice questions](https://engineeringmechanicsoer.github.io/StrengthOfMaterialsExercises/). These questions are a mix of (1) new questions generated by the author team and (2) adapted questions from Kurt Gramoll's Eng Mechanics question bank (accessible via the [Apple Store](https://apps.apple.com/us/app/eng-mechanics/id1526030024) or [Google Play](https://play.google.com/store/apps/details?id=air.com.gramago.engProbME&pli=1)).

### Forthcoming in 2026

-   A print version, made available for purchase through Amazon

-   A PDF version

-   An EPUB version

## Helpful Links

**Are you reviewing or adopting this book for a course?** Please help us understand your use by filling out [**this form**](https://bit.ly/interest_strengthofmaterials).

**Error reporting.** If you spot an error in this book, please let us know by filling out [this form](https://bit.ly/reporterror_strengthofmaterials). You can view known errata [here](https://bit.ly/errata_strengthofmaterials).

## Copyright Information

**© James K. Lord, Amy Richardson, Sneha Davison, and David A. Dillard, 2025.** *Strength of Materials* by James K. Lord, Amy Richardson, Sneha Davison, and David A. Dillard is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License, except where otherwise noted.

**You are free** to copy, share, adapt, remix, transform, and build on the material for any purpose as long as you follow the terms of the license: <https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en>.

**You must:**

-   Attribute—You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

-   ShareAlike—If you remix, transform, or build on the material, you must distribute your contributions under the same license as the original.

**You may not**:

-   NonCommercial—You may not use the material for commercial purposes.

-   Additional restrictions—You may not add any legal terms or technological measures that legally restrict others from doing anything the license permits.

**Attribution:** The American Institute of Steel Construction ("AISC") granted exclusive consent to the authors to reprint portions of the Steel Construction Manual, 16^th^ ed. This material appears in Appendix A. *Copyright © American Institute of Steel Construction Reprinted with permission. All rights reserved.*

**Suggested citation**: James K. Lord, Amy Richardson, Sneha Davison, and David A. Dillard, *Strength of Materials* (Virginia Tech Press, 2025). CC BY-NC-SA 4.0. <https://doi.org/10.21061/strengthofmaterials>.

**Publisher**: This work is published by Virginia Tech Press.

*Virginia Tech Press*

560 Drillfield Drive Blacksburg, VA 24061 USA

<https://publishing.vt.edu> \| [publishing\@vt.edu](#0)

**Peer review**: This book has undergone single-anonymous peer review by four reviewers.

**Accessibility statement**: Virginia Tech is committed to making its publications accessible in accordance with the Americans with Disabilities Act of 1990. The text, images, and links are tagged structurally and include alternative text, which allows for machine readability. Virginia Tech Press is continuously working to improve accessibility and welcomes any feedback from readers.

**Disclaimer:** The information provided in this text is of an introductory nature and cannot substitute for design or sector-specific advice of an engineering professional. The information is presented as-is for educational purposes without any warranty of any kind.

**Funding:** This project was made possible in part through financial support from Virginia’s Academic Library Consortium Open Grant, the University Libraries’ Open Education Initiative, and Virginia Tech’s Department of Engineering Education.

**Cataloging-in-Publication Data**

Lord, James K., Richardson, Amy, Davison, Sneha, and Dillard, David A.

Strength of Materials / James K. Lord, Amy Richardson, Sneha Davison, and David A. Dillard

Pages cm

ISBN 978- (PDF)

ISBN 978- (EPUB)

ISBN 978- (HTML)

ISBN 978- (Print)

DOI: <https://doi.org/10.21061/strengthofmaterials>

Deformations (Mechanics)--Textbooks.

Strength of materials--Textbooks.

TA417.6 .L67 2025

**Cover design**: Kindred Grey
