<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Mechanics of Deformable Bodies - 8&nbsp; Geometric Properties</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Chapter 9.html" rel="next">
<link href="./Chapter 7.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/custom.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Chapter 8.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Geometric Properties</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Mechanics of Deformable Bodies</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Statics Review</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Stress</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Strain</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Mechanical Properties of Materials</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Axial Loading</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Torsion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Beams</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 8.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Geometric Properties</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bending Loads</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Shear Loads</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Beam Deflection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Stress Transformation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Thin-Walled Pressure Vessels</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Combined Loads</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Columns</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix A.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Geometric Properties of Standard Beams</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix B.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Slope and Deflection Tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix C.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Material Properties</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix D.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Units and Order of Magnitude</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#sec-8.1" id="toc-sec-8.1" class="nav-link" data-scroll-target="#sec-8.1"><span class="header-section-number">8.1</span> Centroid</a></li>
  <li><a href="#sec-8.2" id="toc-sec-8.2" class="nav-link" data-scroll-target="#sec-8.2"><span class="header-section-number">8.2</span> 2<sup>nd</sup> Moment of Areas</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-geometric-properties" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Geometric Properties</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Define the centroids of areas.</li>
<li>Locate the centroid using composite parts.</li>
<li>Explain the principles behind determining the second moment of area (moment of inertia).</li>
<li>Apply the parallel-axis theorem to analyze the transformation of moments of inertia.</li>
</ul>
</div>
</div>
<section id="introduction" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="introduction">Introduction</h2>
<details open="">
<summary>
Click to expand
</summary>
<p>As we found in previous chapters, geometric cross-section properties are critical to calculating stresses and deformations for members subjected to axial and torsional loads. The same is true for finding stresses and deflections in beams subjected to shear and bending loads. This chapter describes methods for finding section properties necessary to calculate the stress and deflection in beams. Specifically, the centroid and the second moment of area.</p>
<p>You likely were presented with these topics in Statics, so this chapter is designed to be a review. Section 8.1 will review centroids and Section 8.2 will review area moments of inertia (also known as the 2<sup>nd</sup> moment of area).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/figure 8.1.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="314"></p>
<figcaption>Figure 8.1: Isometric view of concrete barriers used in roadway construction.</figcaption>
</figure>
</div>
</details>
</section>
<section id="sec-8.1" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="sec-8.1"><span class="header-section-number">8.1</span> Centroid</h2>
<details>
<summary>
Click to expand
</summary>
<p>An object possesses weight due to the gravitational force acting on its constituent particles. The collective effect of these forces yields the total weight of the object, which is concentrated at a single point known as the <strong>center of gravity</strong>. If the object is comprised of a homogenous (constant density) material, then the center of gravity is the same as the geometric center or centroid. In this section, we will focus our discussions on the centroid of an area for common structural shapes. For a more comprehensive discussion on the center of gravity, the center of mass, calculating centroids using integration, and distributed loads, see the <a href="https://engineeringstatics.org/Chapter_07-center-of-mass.html">Engineering Statics</a> book by Baker and Haynes.</p>
<p>The location of the centroid of an area is the point where the first moment of area equals zero. The first moment of area about a point is calculated by multiplying the area by the perpendicular distance to the point. The centroid of an area can be found by splitting the area into a number (i) of discrete parts, summing the moment of area for these discrete parts, and then dividing by the sum of the area. We can use these weighted averages to find the location <span class="math inline">\((\bar{X}, \bar{Y})\)</span> of the centroid of the area:</p>
<p><span id="eq-8.1"><span class="math display">\[
\boxed{\begin{aligned}
&amp;\bar{X}=\frac{\sum \bar{x}_i A_i}{\sum A_i} \\
\\
&amp;\bar{Y}=\frac{\sum \bar{y}_i A_i}{\sum A_i}
\end{aligned}}
\tag{8.1}\]</span></span></p>
<div class="line-block"><em>where</em><br>
<span class="math inline">\(\bar{X}, \bar{Y}\)</span> <em>= Centroid coordinates of the overall area [m, in.]</em><br>
<span class="math inline">\(\bar{x}_i, \bar{y}_i\)</span> <em>= Centroid coordinates of each discrete area [m, in.]</em></div>
<p><span class="math inline">\(A_i\)</span> <em>= Area of each discrete area [m<sup>2</sup>, in.<sup>2</sup>]</em></p>
<p>We can find centroids of simple shapes easily by utilizing symmetry. When a shape possesses an axis of symmetry, each point on one side of the axis corresponds to another point symmetrically located on the opposite side. The distances between these mirrored points and the line of symmetry will sum to zero because they will be equal in magnitude but opposite in sign. This is true for every point in the shape, so the numerator of <a href="#eq-8.1" class="quarto-xref">Equation&nbsp;<span class="quarto-unresolved-ref">eq-8.1</span></a> (the first moment of area) will be zero. Therefore, if a shape features a line of symmetry, its centroid must coincide with this line. In cases where a shape exhibits multiple lines of symmetry, the centroid is located at their intersection, as shown in Figure 8.2.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/figure 8.2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="355"></p>
<figcaption>Figure 8.2: Centroids lie upon axes of symmetry.</figcaption>
</figure>
</div>
<p>In this text, we will use common shapes or a composite of common shapes for our cross-sections. Appendix E includes the location of the centroid of some common shapes. Part of Appendix E is reproduced in Figure 8.3. Each row of the table includes a common shape with the centroid marked, and simple formulas for determining the x- and y-coordinates of the centroid and calculating the area of the shape.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/figure 8.3.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
<figcaption>Figure 8.3: Reproduction of one of the shapes in Appendix E. Appendix E includes a sketch of the area with the centroid marked, formulas for determining the x- and y-coordinates of the centroid, and a formula for calculating the area of the shape.</figcaption>
</figure>
</div>
<p>Often, structural sections are combinations of these standard shapes called composite sections. As long as we know the location of the centroid of each shape that comprises the section, we will not need to use integration to find the location of the overall sections’ centroid. We can use <a href="#eq-8.1" class="quarto-xref">Equation&nbsp;<span class="quarto-unresolved-ref">eq-8.1</span></a> in conjunction with the table in Appendix E to find the location of the centroid for composite shapes.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 8.1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Find the centroid of the shape below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.1 part 1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="305"></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>For this T-section, we notice that it is symmetric about the y-axis. This means we will not need to calculate the centroid in the x direction because we know it will be on that y-axis. We only need to find the distance in the y direction, <span class="math inline">\(\bar{Y}\)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.1 part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="245"></p>
</figure>
</div>
<p>The first thing we need to do is establish a coordinate system where the origin is our reference point, RP. In this example we chose the bottom left corner of the section so that all of our y distances will be positive.</p>
<p>We then divide the section into simpler shapes where we know the location of the centroid. In this case we chose two rectangles, labeled 1 and 2 in the figure.</p>
<table class="table">
<thead>
<tr class="header">
<th>Shape</th>
<th><span class="math inline">\(A{~(in.^2)}\)</span></th>
<th><span class="math inline">\(\bar{y}{~(in.)}\)</span></th>
<th><span class="math inline">\(A\bar{y}{~(in.^3)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>13.5</td>
<td>2.25</td>
<td>30.375</td>
</tr>
<tr class="even">
<td>2</td>
<td>13.5</td>
<td>5.25</td>
<td>70.875</td>
</tr>
<tr class="odd">
<td></td>
<td><span class="math inline">\(\sum A\)</span>=27</td>
<td></td>
<td><span class="math inline">\(\sum A\bar{y}\)</span>=101.25</td>
</tr>
</tbody>
</table>
<p>Next, we will create a table with columns titled Shape, <span class="math inline">\(A\)</span> (in.<sup>2</sup>), <span class="math inline">\(\bar{y}\)</span> (in.), and <span class="math inline">\(A\bar{y}\)</span> (in.<sup>3</sup>). We have two shapes so there will be two rows in our table. The first column, Area, is the area of the individual shape. The second column, <span class="math inline">\(\bar{y}\)</span>, is the perpendicular distance in the y-direction from the RP to the centroid of that shape. For example, for shape 1 the <span class="math inline">\(\bar{y_1}\)</span> would be half of 4.5 inches since the bottom of shape 1 aligns with the RP. However, for shape 2 the <span class="math inline">\(\bar{y_2}\)</span> would be 4.5 inches plus one half of 1.5 inches. This is because we need to ensure that we are measuring from the RP as illustrated below.</p>
<p><span class="math display">\[
\bar{Y}=\frac{101.25{~in.^3}}{27{~in.^2}}=3.75{~in.} ~~\text{from bottom}
\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.1 part 3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="481"></p>
</figure>
</div>
<p>Finally, to calculate the centroid coordinates, we will utilize <a href="#eq-8.1" class="quarto-xref">Equation&nbsp;<span class="quarto-unresolved-ref">eq-8.1</span></a> by summing the last column and the second column in our table. We found the centroid to be 3.75 inches from the reference point in the y-direction and on the line of symmetry in the x-direction. The figure below show the location of the centroid for this T section.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.1 part 4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="350"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 8.2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Find the centroid of the shape below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.2 part 1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="280"></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>For this section, we notice that it is symmetric about the y-axis, similar to the previous example. This means that we will not need to calculate the centroid in the x direction because we know it will be on that y-axis. We only need to find the distance in the y direction, <span class="math inline">\(\bar{Y}\)</span>.</p>
<p>The first thing we need to do is establish a coordinate system whose origin is our reference point, RP. In this example, we chose the bottom of the section along the y-axis so that all of our y distances will be positive.</p>
<p>We then divide the section into simpler shapes for which we know the centroid’s location. In this case, we chose three rectangles labeled 1, 2, and 3 in the figure.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.2 part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="284"></p>
</figure>
</div>
<p>Next, we will create a table with columns titled Shape, <span class="math inline">\(A\)</span> (mm<sup>2</sup>), <span class="math inline">\(\bar{y}\)</span> (mm), and <span class="math inline">\(A\bar{y}\)</span> (mm<sup>3</sup>). We have three shapes, so there will be three rows. The first column, Area, is the area of the individual shape. The second column, <span class="math inline">\(\bar{y}\)</span>, is the perpendicular distance in the y-direction from the RP to the centroid of that shape. The figure below shows how the <span class="math inline">\(\bar{y}\)</span> for each shape is calculated.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.2 part 3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
<p>Find centroid (x̄=0 due to symmetry).</p>
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 21%">
<col style="width: 23%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Shape</th>
<th><span class="math inline">\(A{~(mm^2)}\)</span></th>
<th><span class="math inline">\(\bar{y}{~(mm)}\)</span></th>
<th><span class="math inline">\(A\bar{y}{~(mm^3)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>4,000</td>
<td>20</td>
<td>80,000</td>
</tr>
<tr class="even">
<td>2</td>
<td>2,800</td>
<td>110</td>
<td>308,000</td>
</tr>
<tr class="odd">
<td>3</td>
<td>7,200</td>
<td>200</td>
<td>1,440,000</td>
</tr>
<tr class="even">
<td></td>
<td><span class="math inline">\(\sum A\)</span>=14,000</td>
<td></td>
<td><span class="math inline">\(\sum A\bar{y}\)</span>=1,828,000</td>
</tr>
</tbody>
</table>
<p>Finally, to calculate the centroid coordinates, we will utilize <a href="#eq-8.1" class="quarto-xref">Equation&nbsp;<span class="quarto-unresolved-ref">eq-8.1</span></a> by summing the second and last columns in our table.</p>
<p><span class="math display">\[
\bar{Y}=\frac{1,828,000{~mm^3}}{14,000{~mm^2}}=130.6{~mm} ~~\text{from bottom}
\]</span></p>
<p>We found the centroid to be 130.6 mm from the reference point in the y-direction and on the line of symmetry in the x-direction. The figure below shows the location of the centroid for this section.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.2 part 4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="366"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 8.3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Find the centroid of the shape below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.3 part 1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="497"></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This section does not have any axis of symmetry, so we will need to find both the <span class="math inline">\(\bar{x}\)</span> and the <span class="math inline">\(\bar{y}\)</span>. We first need to establish a coordinate system whose origin is our reference point, RP. In this example, we will use the coordinate axis in the problem to illustrate when <span class="math inline">\(\bar{x}\)</span> will be negative.</p>
<p>We then divide the section into simpler shapes for which we know the centroid’s location. In this case, we will break this up into the square, triangle, and circle labeled 1, 2, and 3 in the figure. Note that the circle is a hole, and the area will be represented as negative.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.3 part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="487"></p>
</figure>
</div>
<p>Next, we will create a table with columns titled Shape, <span class="math inline">\(A\)</span> (in<sup>2</sup>), <span class="math inline">\(\bar{x}\)</span> (in), <span class="math inline">\(\bar{y}\)</span> (in), and <span class="math inline">\(A\bar{y}\)</span> (in<sup>3</sup>). We have three shapes so there will be three rows. The first column, Area, is the area of the individual shape. The second column, <span class="math inline">\(\bar{x}\)</span>, is the perpendicular distance in the x-direction from the RP to the centroid of that shape. The figure below shows how the <span class="math inline">\(\bar{x}\)</span> for each shape is calculated.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.3 part 3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="496"></p>
</figure>
</div>
<p>The figure below shows how the <span class="math inline">\(\bar{y}\)</span> for each shape is calculated.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.3 part 4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="498"></p>
</figure>
</div>
<p>Finally, to calculate the centroid coordinates, we will utilize <a href="#eq-8.1" class="quarto-xref">Equation&nbsp;<span class="quarto-unresolved-ref">eq-8.1</span></a> by summing the Area, <span class="math inline">\(A\bar{x}\)</span>, and <span class="math inline">\(A\bar{y}\)</span> columns see the table below.</p>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 18%">
<col style="width: 14%">
<col style="width: 17%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Shape</strong></td>
<td><strong>Shape</strong></td>
<td><span class="math inline">\(A{~(in.^2)}\)</span></td>
<td><span class="math inline">\(\bar{x}{~(in.)}\)</span></td>
<td><span class="math inline">\(A\bar{x}{~(in.^3)}\)</span></td>
<td><span class="math inline">\(\bar{y}{~(in.)}\)</span></td>
<td><span class="math inline">\(A\bar{y}{~(in.^3)}\)</span></td>
</tr>
<tr class="even">
<td></td>
<td>1</td>
<td>64</td>
<td>-4</td>
<td>-256</td>
<td>4</td>
<td>256</td>
</tr>
<tr class="odd">
<td></td>
<td>2</td>
<td>24</td>
<td>2</td>
<td>48</td>
<td>(2/3)(8) = 16/3</td>
<td>128</td>
</tr>
<tr class="even">
<td></td>
<td>3</td>
<td>-4π</td>
<td>-4</td>
<td>-16π</td>
<td>4</td>
<td>-16π</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td><span class="math inline">\(\sum A\)</span>=75.4</td>
<td></td>
<td><span class="math inline">\(\sum A\bar{x}\)</span>=-258.3</td>
<td></td>
<td><span class="math inline">\(\sum A\bar{y}\)</span>=333.7</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\begin{aligned}
&amp; \bar{X}=\frac{\sum A \bar{x}}{\sum A}=\frac{-258.3{~in.^3}}{75.4{~in.^2}} \quad\rightarrow\quad \bar{X}=-3.43{~in} \\
&amp; \bar{Y}=\frac{\sum A \bar{y}}{\sum A}=\frac{333.7{~in.^3}}{75.4{~in.^2}} \quad\rightarrow\quad \bar{Y}=4.43 \mathrm{in}
\end{aligned}
\]</span></p>
<p>We found the centroid to be -3.43 inches in the x-direction from the reference point, this indicates that the centroid will be to the left of the y-axis. The y-component of the centroid is 4.43 inches in the y-direction from the reference point. The figure below shows the location of the centroid for this section.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.3 part 5.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="507"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Step-by-step: Finding the Centroid of Composite Sections
</div>
</div>
<div class="callout-body-container callout-body">
<p>To find the location of the centroid of a composite section where the location of the centroid is known for each part of the composite section, use the following procedure:</p>
<ol type="1">
<li>Establish a coordinate axis where the origin is the reference point (RP). This will be where the centroid will be measured.</li>
<li>Break the overall section up into simpler shapes where the location of the centroid of each shape is known. It is helpful here to sketch this. If the section has a hole, include the hole as a shape with a negative area. Remember to take advantage of symmetry. If the overall section is symmetric about an axis, you already know the location of the centroid in that direction as it is on that axis.</li>
<li>Determine the Area (A), the perpendicular distance from the y-axis (<span class="math inline">\(\bar{x}\)</span>), and the perpendicular distance from the x-axis (<span class="math inline">\(\bar{y}\)</span>) to the centroid of each shape. As sections become more complex, it might be advantageous to arrange these values in tabular form (see examples in this section).</li>
<li>Apply <a href="#eq-8.1" class="quarto-xref">Equation&nbsp;<span class="quarto-unresolved-ref">eq-8.1</span></a> to find the overall section’s centroid, (<span class="math inline">\(\bar{X}, \bar{Y}\)</span>). Remember that this location is measured from the RP you established in step 1.</li>
<li>Check that your answer is reasonable. Imagine any straight line that passes through the centroid. There should be an equal amount of area on each side of this line. Mark the centroid location on the composite area and check that this appears roughly accurate.</li>
</ol>
</div>
</div>
</details>
</section>
<section id="sec-8.2" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="sec-8.2"><span class="header-section-number">8.2</span> 2<sup>nd</sup> Moment of Areas</h2>
<details>
<summary>
Click to expand
</summary>
<p>Another important geometric property needed to calculate stresses in beams is the Moment of Inertia of the Area (2<sup>nd</sup> moment of area). Similar to our discussion of centroids, you likely were presented this topic in Statics so this chapter is designed to be a review. By definition, the second moment of area or moment of inertia depicted in Figure 8.4 is defined as:</p>
<p><span id="eq-8.2"><span class="math display">\[
\boxed{\begin{aligned}
&amp;I_x=\int_A y^2 d A \\
&amp;I_y=\int_A x^2 d A \\
&amp;I_z=J=\int_A r^2 d A \\
\end{aligned}}
\tag{8.2}\]</span></span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/figure 8.4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="439"></p>
<figcaption>Figure 8.4: Moments of inertia of an area dA.</figcaption>
</figure>
</div>
<p>In this text, we will use common shapes or a composite of common shapes for our cross-sections. Appendix E includes formulas to calculate the moment of inertia. Part of Appendix E is reproduced in figure 8.5. Each row of the table includes a common shape with the centroid marked, and formulas for determining the moment of inertia of the area about the x-, y-, and z-centroidal axes. Note that these equations are valid only for the axes passing through the centroid of the area and are written as <span class="math inline">\(\overline{I_{x^{\prime}}}\)</span>, <span class="math inline">\(\overline{I_{y^{\prime}}}\)</span>, and J respectively. The bar notation is used to signify that the moment of inertia is being calculated around the centroidal axes.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/figure 8.5.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
<figcaption>Figure 8.5: Reproduction of one of the shapes in Appendix E. Appendix E includes a sketch of the area with the centroid marked, and formulas for determining the moment of inertia of the area about the x-, y-, and z-centroidal axes.</figcaption>
</figure>
</div>
<p>As noted previously, structural sections are often combinations of these standard shapes called composite sections. Similar to calculating centroids we will break these composite sections into common shapes and find the moment of inertia of these individual shapes.&nbsp; When we calculate each individual shape’s moment of inertia, we need to ensure that they are all about the same axis. The <strong>parallel axis theorem</strong> provides a method for calculating the moment of inertia of an area about an axis parallel to an axis passing through the centroid, given that the moment of inertia about the latter axis is known.</p>
<p>To establish the parallel axis theorem, we will examine the moment of inertia <em>I</em> of an area <em>A</em> relative to an axis <em>x</em>, as illustrated in Figure 8.6.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/figure 8.6.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="430"></p>
<figcaption>Figure 8.6: The moment of inertia of an area A about an axis x can be derived from its moment of inertia about the centroidal axis x’ through a computation involving the distance dy between the axes.</figcaption>
</figure>
</div>
<p>The centroid of the area is at C, where the x’-y’ axis is drawn; note that x’ is parallel to x and y’ is parallel to y. The x-y’ axes will be termed the centroidal axes and a distance of dx and dy from the x-y axes, respectively. The distance between the element dA and the x’-axis is denoted as y’. Now we have <span class="math inline">\(y=y^{\prime}+d_y\)</span>. Substituting into <a href="#eq-8.2" class="quarto-xref">Equation&nbsp;<span class="quarto-unresolved-ref">eq-8.2</span></a>, we have:</p>
<p><span class="math display">\[
\begin{aligned}
&amp; I_x=\int\left(y^{\prime}+d_y\right)^2 d A \\
&amp; I_x=\int\left(y^{\prime}\right)^2 d A+2 d_y \int y^{\prime} d A+d_y^2 \int d A
\end{aligned}
\]</span></p>
<p>The first integral represents the moment of inertia about the centroidal axis x’. The second integral is zero since the centroid is located on the x’ axis (i.e., <span class="math inline">\(\int y^{\prime} d A\)</span> represents the first moment of area about the x’ centroidal axis, which is zero as discussed in section 8.1). The last integral represents the total area, A. So we have:</p>
<p><span id="eq-8.3"><span class="math display">\[
\boxed{I_x=\overline{I_{x^{\prime}}}+A d_y^2}
\tag{8.3}\]</span></span></p>
<p>A similar process is used to find an expression for I<sub>y</sub>:</p>
<p><span id="eq-8.4"><span class="math display">\[
\boxed{I_y=\overline{I_{y^{\prime}}}+A d_x^2}
\tag{8.4}\]</span></span></p>
<div class="line-block"><em>where</em><br>
<em>I<sub>x</sub>, I<sub>y</sub> = the moment of inertia of an area with respect to a given axis [m<sup>4</sup>, in.<sup>4</sup>]</em><br>
<span class="math inline">\(\overline{I_{x^{\prime}}}\)</span> <em>,</em> <span class="math inline">\(\overline{I_{y^{\prime}}}\)</span> <em>= moment of inertia of that area with respect to a parallel axis passing through the centroid of the area [m<sup>4</sup>, in.<sup>4</sup>]</em><br>
<em>A = area [m<sup>2</sup>, in.<sup>2</sup>]</em></div>
<p><em>d<sub>x</sub>, d<sub>y</sub> = perpendicular distance between the given axis and the parallel centroidal axis [m, in.]</em></p>
<p>While the parallel axis theorem can be used to calculate the area moment of inertia around any pair of axes, we will primarily focus on calculating the area moment of inertia around the centroidal axes of a composite area. It is this term which will be used in chapters 9 and 10 when calculating bending stresses and shear stresses.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 8.4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Determine the I<sub>x</sub> the shaded area with respect to the section’s centroid.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.4 part 1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="310"></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Since we want to find the moment of inertia in the x direction with respect to the section’s centroid, we first need to calculate the centroid. We did this in Example 8.1, the results are shown below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.4 part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="390"></p>
</figure>
</div>
<p>We found that the centroid is located 3.75 inches from the bottom of the section. The next step is to break the section into common shapes as noted in the figure below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.4 part 3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="357"></p>
</figure>
</div>
<p>The formulas for moment of inertia of each shape are with respect to the shape’s centroid not the overall section’s centroid. We will need to make and adjustment using the parallel-axis theorem to transform the rotational axis from the shape’s centroid to the section’s centroid. We will present this method in terms of a table.</p>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 16%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Shape</th>
<th><span class="math inline">\(A{~(in.^2)}\)</span></th>
<th><span class="math inline">\(I_x{~(in.^4)}\)</span></th>
<th><span class="math inline">\(d_y{~(in.)}\)</span></th>
<th><span class="math inline">\(I_x+Ad_y^2{~(in.^4)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><p>(3)(4.5) =</p>
<p>13.5</p></td>
<td><p>(1/12)(3)(4.5)<sup>3</sup> =</p>
<p>22.78125</p></td>
<td>1.5</td>
<td><p>22.78125 + (13.5)(1.5)<sup>2</sup> =</p>
<p>53.15625</p></td>
</tr>
<tr class="even">
<td>2</td>
<td><p>(9)(1.5) =</p>
<p>13.5</p></td>
<td><p>(1/12)(9)(1.5)<sup>3</sup> =</p>
<p>2.53125</p></td>
<td>1.5</td>
<td><p>2.53125 + (13.5)(1.5)<sup>2</sup> =</p>
<p>32.90625</p></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td>I<sub>x</sub>=86.0625 in<sup>4</sup></td>
</tr>
</tbody>
</table>
<p>The calculation and visualizations for each d<sub>y</sub> term are shown in the figure below</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.4 part 4.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 8.5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Determine the I<sub>x</sub> and I<sub>y</sub> of the shaded area with respect to the shapes centroid.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.5 part 1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="289"></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Since we want to find the moment of inertia in the x and y directions with respect to the section’s centroid, we first need to calculate the centroid. We did this in Example 8.2, the results are shown below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.5 part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="358"></p>
</figure>
</div>
<p>We found that the centroid is located 130.6 mm from the bottom of the section and on the y-axis. The next step is to break the section into common shapes as noted in the figure below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.5 part 3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="318"></p>
</figure>
</div>
<p>The formulas for moment of inertia of each shape are with respect to the shape’s centroid not the overall section’s centroid. We will need to make and adjustment using the parallel-axis theorem to transform the rotational axis from the shape’s centroid to the section’s centroid. We will present this method in terms of a table, first for I<sub>x</sub>.</p>
<table class="table">
<colgroup>
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 22%">
<col style="width: 14%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Shape</th>
<th><span class="math inline">\(A{~(in.^2)}\)</span></th>
<th><span class="math inline">\(I_x{~(in.^3)}\)</span></th>
<th><span class="math inline">\(d_y{~(mm)}\)</span></th>
<th><span class="math inline">\(I_x+Ad_y^2{~(mm^4)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><p>(100)(40) =</p>
<p>4,000</p></td>
<td><p>(1/12)(100)(40)<sup>3</sup> =</p>
<p>533,333</p></td>
<td>110.57</td>
<td><p>533,333 + (4,000)(110.57)<sup>2</sup> =</p>
<p>49,436,233</p></td>
</tr>
<tr class="even">
<td>2</td>
<td><p>(20)(140) =</p>
<p>2,800</p></td>
<td><p>(1/12)(20)(140)<sup>3</sup> =</p>
<p>4,573,333</p></td>
<td>20.57</td>
<td><p>4573,333 + (2,800)(20.57)<sup>2</sup> =</p>
<p>5,758,083</p></td>
</tr>
<tr class="odd">
<td>3</td>
<td><p>(180)(40) =</p>
<p>7,200</p></td>
<td><p>(1/12)(180)(40)<sup>3</sup> =</p>
<p>960,000</p></td>
<td>69.43</td>
<td><p>960,000 + (7,200)(69.43)<sup>2</sup> =</p>
<p>35,667,779</p></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td>I<sub>x</sub> = 90,862,095 mm<sup>4</sup></td>
</tr>
</tbody>
</table>
<p>The calculation and visualizations for each d<sub>y</sub> term are shown in the figure below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.5 part 4.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>We will do the same process to calculate I<sub>y</sub>.</p>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 23%">
<col style="width: 15%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Shape</th>
<th><span class="math inline">\(A{~(mm^2)}\)</span></th>
<th><span class="math inline">\(I_y{~(mm^4)}\)</span></th>
<th><span class="math inline">\(d_x{~(mm)}\)</span></th>
<th><span class="math inline">\(I_y+Ad_x^2{~(mm^4)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><p>(100)(40) =</p>
<p>4,000</p></td>
<td><p>(1/12)(40)(100)<sup>3</sup> =</p>
<p>3,333,333</p></td>
<td>0</td>
<td><p>3,333,333 + (4,000)(0)<sup>2</sup> =</p>
<p>3,333,333</p></td>
</tr>
<tr class="even">
<td>2</td>
<td><p>(20)(140) =</p>
<p>2,800</p></td>
<td><p>(1/12)(140)(20)<sup>3</sup> =</p>
<p>93,333</p></td>
<td>0</td>
<td><p>93,333 + (2,800)(0)<sup>2</sup> =</p>
<p>93,333</p></td>
</tr>
<tr class="odd">
<td>3</td>
<td><p>(180)(40) =</p>
<p>7,200</p></td>
<td><p>(1/12)(40)(180)<sup>3</sup> =</p>
<p>19,440,000</p></td>
<td>0</td>
<td><p>19,440,000 + (7,200)(0<sup>2</sup> =</p>
<p>19,440,000</p></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td>I<sub>y</sub> = 22,866,667 mm<sup>4</sup></td>
</tr>
</tbody>
</table>
<p>Notice that the values for d<sub>x</sub> are all zero when calculating I<sub>y</sub>. This is because the centroid of each shape coincides with the centroid of the entire section therefore the distance between them is zero.</p>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 8.6: Moment of Inertia
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Determine the I<sub>x</sub> and I<sub>y</sub> of the shaded area with respect to the shape’s centroid.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.6 part 1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="404"></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Since we want to find the moment of inertia in the x and y directions with respect to the section’s centroid, we first need to calculate the centroid. We did this in Example 8.3, the results are shown below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.6 part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="450"></p>
</figure>
</div>
<p>We found that the centroid is located 3.43 inches to the left of the y-axis and 4.43 inches up from the x-axis. The next step is to break the section into common shapes as noted in the figure below. Notice that shape 3 is a hole so we will need to subtract the moment of inertia and area.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.6 part 3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="545"></p>
</figure>
</div>
<p>The formulas for moment of inertia of each shape are with respect to the shape’s centroid not the overall section’s centroid. We will need to make and adjustment using the parallel-axis theorem to transform the rotational axis from the shape’s centroid to the section’s centroid.&nbsp; We will present this method in terms of a table, first for I<sub>x</sub> then I<sub>y</sub>.</p>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 19%">
<col style="width: 15%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Shape</th>
<th>Shape</th>
<th><span class="math inline">\(A{~(in.^2)}\)</span></th>
<th><span class="math inline">\(I_x{~(in.^4)}\)</span></th>
<th><span class="math inline">\(d_y{~(in.)}\)</span></th>
<th><span class="math inline">\(I_x+Ad_y^2{~(in.^4)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>1</td>
<td>64</td>
<td><p>(1/12)(8)(8)<sup>3</sup> =</p>
<p>341.3</p></td>
<td>0.43</td>
<td><p>341.3 + (64)(0.43)<sup>2</sup> =</p>
<p>353.1</p></td>
</tr>
<tr class="even">
<td></td>
<td>2</td>
<td>24</td>
<td><p>(1/36)(6)(8)<sup>3</sup> =</p>
<p>85.3</p></td>
<td>0.90</td>
<td><p>85.3 + (24)(0.9)<sup>2</sup> =</p>
<p>104.7</p></td>
</tr>
<tr class="odd">
<td></td>
<td>3</td>
<td>-4π</td>
<td><p>(-1/4π)(2)<sup>4</sup> =</p>
<p>-12.6</p></td>
<td>0.43</td>
<td><p>-12.6 + (-4π)(0.43)<sup>2</sup> =</p>
<p>-14.9</p></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>I<sub>x</sub> = 442.9 in<sup>4</sup></td>
</tr>
</tbody>
</table>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 19%">
<col style="width: 15%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Shape</th>
<th>Shape</th>
<th><span class="math inline">\(A{~(in.^2)}\)</span></th>
<th><span class="math inline">\(I_y{~(in.^4)}\)</span></th>
<th><span class="math inline">\(d_x{~(in.)}\)</span></th>
<th><span class="math inline">\(I_y+Ad_x^2{~(in.^4)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>1</td>
<td>64</td>
<td><p>(1/12)(8)(8)<sup>3</sup> =</p>
<p>341.3</p></td>
<td>0.57</td>
<td><p>341.3 + (64)(0.57)<sup>2</sup> =</p>
<p>362.1</p></td>
</tr>
<tr class="even">
<td></td>
<td>2</td>
<td>24</td>
<td><p>(1/36)(8)(6)<sup>3</sup> =</p>
<p>48</p></td>
<td>1.43</td>
<td><p>48 + (24)(1.43)<sup>2</sup> =</p>
<p>97.1</p></td>
</tr>
<tr class="odd">
<td></td>
<td>3</td>
<td>-4π</td>
<td><p>(-1/4π)(2)<sup>4</sup> =</p>
<p>-12.6</p></td>
<td>0.57</td>
<td><p>-12.6 + (-4π)(0.57)<sup>2</sup> =</p>
<p>-16.7</p></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>I<sub>y</sub> = 442.5 in<sup>4</sup></td>
</tr>
</tbody>
</table>
<p>The calculation and visualizations for each d<sub>x</sub> and d<sub>y</sub> terms are shown in the figure below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH 8 PNGs/example 8.6 part 4.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Step-by-step: Finding the Moment of Inertia
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use the following steps to find the moment of inertia of a composite section:</p>
<ol type="1">
<li>Determine where you are taking the moment of inertia, about a reference axis or the centroidal axis. If it is about the centroidal axis, calculate the location of the centroid.</li>
<li>Break the overall section up into simpler shapes where the location of the centroid of each shape is known. It is helpful here to sketch this. If the section has a hole, include the hole as a shape with a negative inertia.</li>
<li>Implement the parallel-axis theorem for each individual shape.</li>
<li>Indicate the perpendicular distance from the centroid of each part to the axis that you are calculating the moment of inertia about.</li>
<li>The moment of inertia of the section about an axis is the sum of the composite parts about the same axis.</li>
</ol>
</div>
</div>
</details>
</section>
<section id="summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<details>
<summary>
Click to expand
</summary>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Takeaways
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>The centroid represents the geometric center of a shape.</p></li>
<li><p>The center of gravity will be the same as the centroid only if the material is uniform (homogenous).</p></li>
<li><p>The centroid will be located on any axis of symmetry for the section.</p></li>
<li><p>In some cases, the centroid of a shape is not located within the shape itself (as shown in the rightmost section in figure 8.2).</p></li>
<li><p>The moment of inertia represents a geometric property of an area and is occasionally termed as the second moment of the area about an axis, as it involves squaring the distance from the axis to each element of the area.</p></li>
<li><p>The parallel-axis theorem is used to compute the moment of inertia of composite sections.</p></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Equations
</div>
</div>
<div class="callout-body-container callout-body">
<p>Centroid Formulas</p>
<p><span class="math display">\[
\bar{X}=\frac{\sum \bar{x}_i A_i}{\sum A_i}
\]</span></p>
<p><span class="math display">\[
\bar{Y}=\frac{\sum \bar{y}_i A_i}{\sum A_i}
\]</span></p>
<p>Moment of Inertia (Second Moment of Area)</p>
<p><span class="math display">\[
I_x=\int_A y^2 d A
\]</span></p>
<p><span class="math display">\[
I_y=\int_A x^2 d A
\]</span></p>
<p><span class="math display">\[
I_z=J=\int_A r^2 d A
\]</span></p>
<p>Parallel Axis Theorem</p>
<p><span class="math display">\[
I_x=\overline{I_{x^{\prime}}}+A d_y^2
\]</span></p>
<p><span class="math display">\[
I_y=\overline{I_{y^{\prime}}}+A d_x^2
\]</span></p>
</div>
</div>
</details>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Chapter 7.html" class="pagination-link" aria-label="Beams">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Beams</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Chapter 9.html" class="pagination-link" aria-label="Bending Loads">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bending Loads</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>