<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Bending Loads – Strength of Materials</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Chapter 10.html" rel="next">
<link href="./Chapter 8.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9dc9d438c90c12071cf8507e319c8f8e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-afd7089187cf7d32efec5ee34a48d68f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-9dc9d438c90c12071cf8507e319c8f8e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles/custom.css">
</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Chapter 9.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bending Loads</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Strength of Materials</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><strong>About This Book</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Statics Review</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Stress</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Strain</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Mechanical Properties of Materials</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Axial Loading</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Torsion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Beams</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Geometric Properties</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 9.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bending Loads</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Shear Loading in Beams</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Beam Deflection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Stress Transformation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Thin-Walled Pressure Vessels</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Combined Loads</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Columns</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix A.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Geometric Properties of Standard Beams</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix B.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Slope and Deflection Tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix C.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Material Properties</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix D.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Units and Order of Magnitude</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Appendix E.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Centroids and Second Moment of Area for Common Shapes</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-9.1" id="toc-sec-9.1" class="nav-link active" data-scroll-target="#sec-9.1"><span class="header-section-number">9.1</span> Bending Stress</a></li>
  <li><a href="#sec-9.2" id="toc-sec-9.2" class="nav-link" data-scroll-target="#sec-9.2"><span class="header-section-number">9.2</span> Beam Design for Bending</a>
  <ul class="collapse">
  <li><a href="#design-of-standard-steel-sections" id="toc-design-of-standard-steel-sections" class="nav-link" data-scroll-target="#design-of-standard-steel-sections"><span class="header-section-number">9.2.1</span> Design of Standard Steel Sections</a></li>
  <li><a href="#design-of-rectangular-sections" id="toc-design-of-rectangular-sections" class="nav-link" data-scroll-target="#design-of-rectangular-sections"><span class="header-section-number">9.2.2</span> Design of Rectangular Sections</a></li>
  </ul></li>
  <li><a href="#sec-9.3" id="toc-sec-9.3" class="nav-link" data-scroll-target="#sec-9.3"><span class="header-section-number">9.3</span> Unsymmetric Bending—Moment Arbitrarily Applied</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-bending-loads" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bending Loads</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Describe the bending behavior of beams</li>
<li>Calculate the bending stresses in beams</li>
<li>Select an adequate beam, using the section modulus</li>
<li>Analyze beams subjected to unsymmetric bending</li>
</ul>
</div>
</div>
<p>Beams are structural members that support loads along their length. Typically these loads are perpendicular to the axis of the beam and cause only shear forces and bending moments.</p>
<p>As discussed in previous chapters, internal forces and moments and section properties are crucial to calculating stresses and deflections. The same is true for finding stresses and deflections in beams. This chapter describes calculating bending stresses in beams, such as those in <a href="#fig-9.1" class="quarto-xref">Figure&nbsp;<span>9.1</span></a>, with considerations for unsymmetric bending and beam design.</p>
<div id="fig-9.1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Isometric view looking underneath a bridge under construction, showing a series of long prestressed concrete girders spanning horizontally between two supports. The girders cast deep shadows on the gravel-covered ground below, forming a repetitive geometric pattern." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/CH9 PNGs/Figure 9.2.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Isometric view looking underneath a bridge under construction, showing a series of long prestressed concrete girders spanning horizontally between two supports. The girders cast deep shadows on the gravel-covered ground below, forming a repetitive geometric pattern." width="470">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Looking up at bridge beams used to support a landscaped bicycle and pedestrian bridge in Seattle
</figcaption>
</figure>
</div>
<p><a href="#sec-9.1" class="quarto-xref"><span>Section 9.1</span></a> derives an equation for calculating bending stress. <a href="#sec-9.2" class="quarto-xref"><span>Section 9.2</span></a> discusses how to design beams to ensure they don’t fail due to bending stress. <a href="#sec-9.3" class="quarto-xref"><span>Section 9.3</span></a> extends the analysis to include cases where the bending moment not only acts about the horizontal axis of the beam but has components about both the horizontal and the vertical axes.</p>
<section id="sec-9.1" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="sec-9.1"><span class="header-section-number">9.1</span> Bending Stress</h2>
<details>
<summary>
Click to expand
</summary>
<p>This section discusses bending behavior of straight, symmetric, homogeneous beams. Additionally, this section is limited to beams with a cross section that is symmetric with an axis and whose bending moment is around an axis that is perpendicular to the axis of symmetry. Examine the initially unaltered beam depicted in <a href="#fig-9.2" class="quarto-xref">Figure&nbsp;<span>9.2</span></a>, which is characterized by a rectangular cross-section and annotated with both horizontal and vertical grid lines.</p>
<div id="fig-9.2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Horizontal rectangular grid with 5 rows and 20 columns of small blue squares, enclosed by a black border. The uniform array represents the rectangular cross section of an unloaded beam." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/CH9 PNGs/Figure 9.3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Horizontal rectangular grid with 5 rows and 20 columns of small blue squares, enclosed by a black border. The uniform array represents the rectangular cross section of an unloaded beam." width="278">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: An unloaded beam with a rectangular cross section
</figcaption>
</figure>
</div>
<p>When a bending moment is applied, horizontal lines curve, whereas vertical lines remain straight but rotate, as illustrated in <a href="#fig-9.3" class="quarto-xref">Figure&nbsp;<span>9.3</span></a>. The material stretches at the bottom and compresses at the top, creating a neutral surface in between where fibers experience no length change. On a cross-section this surface appears as the neutral axis.</p>
<div id="fig-9.3" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Horizontal curved beam segment with a rectangular grid pattern, symmetric about a vertical axis through point O at the top. The beam forms a circular arc, with dashed lines connecting its ends to point O. Two curved arrows labeled M are placed at the arc ends: clockwise on the left and counterclockwise on the right, representing equal and opposite bending moments. The upper portion of the arc is shorter in length, showing compression, while the lower portion is longer, showing tension. A bold horizontal line through the center of the section marks the neutral axis, where fiber length remains unchanged." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/chapter 9 figure updates/9.3 new.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Horizontal curved beam segment with a rectangular grid pattern, symmetric about a vertical axis through point O at the top. The beam forms a circular arc, with dashed lines connecting its ends to point O. Two curved arrows labeled M are placed at the arc ends: clockwise on the left and counterclockwise on the right, representing equal and opposite bending moments. The upper portion of the arc is shorter in length, showing compression, while the lower portion is longer, showing tension. A bold horizontal line through the center of the section marks the neutral axis, where fiber length remains unchanged." width="269">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.3: The deformation of the beam in <a href="#fig-9.2" class="quarto-xref">Figure&nbsp;<span>9.2</span></a> when subjected to a symmetric bending moment
</figcaption>
</figure>
</div>
<p>We can make a similar observation when a kid’s toy undergoes bending as shown in <a href="#fig-9.4" class="quarto-xref">Figure&nbsp;<span>9.4</span></a>. This toy is subjected to a bending moment in the opposite direction of the beam depicted in <a href="#fig-9.3" class="quarto-xref">Figure&nbsp;<span>9.3</span></a>, and this direction switches the behavior of the top and the bottom surfaces. Notice in <a href="#fig-9.4" class="quarto-xref">Figure&nbsp;<span>9.4</span></a> that the fibers at the top are pulled apart whereas the bottom surface fibers are pushed together.</p>
<div id="fig-9.4" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A black-and-white photo of a metallic helical spring (slinky) arranged in a curved shape on a reflective surface. The spring’s coils loop symmetrically outward from the center, forming a tunnel-like pattern with tightly wound turns, illustrating the spring bent into an arching shape." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/chapter 9 figure updates/9.4.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A black-and-white photo of a metallic helical spring (slinky) arranged in a curved shape on a reflective surface. The spring’s coils loop symmetrically outward from the center, forming a tunnel-like pattern with tightly wound turns, illustrating the spring bent into an arching shape." width="336">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.4: The distortion of a kid’s toy when undergoing bending
</figcaption>
</figure>
</div>
<p>This knowledge about deformations due to bending can be applied to the failure of the column in <a href="#fig-9.5" class="quarto-xref">Figure&nbsp;<span>9.5</span></a>. Notice that the column was fixed at the base and subjected to a transverse force that caused failure. The fibers on the right side of the column failure point were pulled apart, whereas the fibers on the left side of the column failure point were compressed.</p>
<div id="fig-9.5" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A bent, rusted steel column lying on a debris-strewn concrete slab in an outdoor setting. The column has a pronounced curvature near midspan, indicating buckling or bending failure." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/CH9 PNGs/Figure 9.6.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A bent, rusted steel column lying on a debris-strewn concrete slab in an outdoor setting. The column has a pronounced curvature near midspan, indicating buckling or bending failure." width="407">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.5: Column failure due to bending
</figcaption>
</figure>
</div>
<p>We make the following assumptions about deformations due to bending:</p>
<ul>
<li><p>There must be a neutral surface parallel to both the upper and lower surfaces, where the length remains constant.</p></li>
<li><p>Throughout the deformation all cross sections of the beam remain plane and perpendicular to the longitudinal axis.</p></li>
<li><p>The cross section will keep its shape (we’ll ignore the Poisson effects discussed in <a href="Chapter 4.html#sec-4.4" class="quarto-xref"><span>Section 4.4</span></a> of this text).</p></li>
</ul>
<div id="fig-9.6" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Horizontal curved beam segment, symmetric about a vertical axis through point O at the top. The beam forms a circular arc with dashed lines connecting its ends to point O. Two curved arrows labeled M act at the ends: clockwise on the left and counterclockwise on the right, representing equal and opposite bending moments. The neutral surface is shown as arc AB, a horizontal arc through the middle of the rectangular cross section, with A on the left and B on the right. Point C lies at the midpoint of arc AB, where coordinate axes x and y are drawn. Above A, at a vertical distance y, is point A′, and a dashed arc extends from A′ to B′. The distance from O to A is labeled rho, and from O to A′ is rho minus y. The angle between the dashed lines at O is labeled d theta." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/chapter 9 figure updates/9.6 new.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Horizontal curved beam segment, symmetric about a vertical axis through point O at the top. The beam forms a circular arc with dashed lines connecting its ends to point O. Two curved arrows labeled M act at the ends: clockwise on the left and counterclockwise on the right, representing equal and opposite bending moments. The neutral surface is shown as arc AB, a horizontal arc through the middle of the rectangular cross section, with A on the left and B on the right. Point C lies at the midpoint of arc AB, where coordinate axes x and y are drawn. Above A, at a vertical distance y, is point A′, and a dashed arc extends from A′ to B′. The distance from O to A is labeled rho, and from O to A′ is rho minus y. The angle between the dashed lines at O is labeled d theta." width="334">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.6: Element in beam bending
</figcaption>
</figure>
</div>
<p>To understand bending stress in a beam subjected to arbitrary loads, examine a small element extracted from the beam as shown in <a href="#fig-9.6" class="quarto-xref">Figure&nbsp;<span>9.6</span></a>. The derivation of the bending strain equation remains unaffected by the beam type or specific loads. Remember the fundamental definition of normal strain is</p>
<p><span class="math display">\[
\varepsilon=\frac{\Delta L}{L}\text{ .}
\]</span></p>
<p>This equation can be used to calculate the normal strain along AB in the beam.</p>
<p><span class="math display">\[
\varepsilon=\frac{\overline{A^{\prime} B^{\prime}}-\overline{A B}}{\overline{A B}}
\]</span></p>
<p>Distance y is measured relative to the neutral surface and is positive above the neutral surface and negative below. Before bending, line AB is the same length at all y values. During bending, though, line A’B’ shortens above the neutral surface and lengthens below it. By definition the length of the neutral surface doesn’t change and remains the same as length AB. The lengths AB and A’B’ can be described using the radius of curvature (ρ) and the differential angle (dθ) shown in <a href="#fig-9.6" class="quarto-xref">Figure&nbsp;<span>9.6</span></a>.</p>
<p><span class="math display">\[
\begin{gathered}
\overline{A B}=\rho d \theta \\
\overline{A^{\prime} B^{\prime}}=(\rho-y) d \theta
\end{gathered}
\]</span></p>
<p>Now we substitute these lengths into the strain equation.</p>
<p><span class="math display">\[
\varepsilon=\frac{(\rho-y) d \theta-\rho d \theta}{\rho d \theta}
\]</span></p>
<p>Simplifying the equation yields</p>
<p><span class="math display">\[
\begin{gathered}
\varepsilon=\frac{\rho d \theta-y d \theta-\rho d \theta}{\rho d \theta} \\
\varepsilon=\frac{-y d \theta}{\rho d \theta} \\
\varepsilon=-\frac{y}{\rho}
\end{gathered}
\]</span></p>
<p>This relationship shows us that the longitudinal strain, ε, varies linearly with the distance, y, from the neutral surface. The maximum stress occurs at the outermost fibers, the extreme top and bottom of the section. This maximum distance from the neutral surface is designated c.&nbsp;A relationship for the maximum absolute value of the strain, ε<sub>max</sub> can now be calculated.</p>
<p><span class="math display">\[
\begin{gathered}
\frac{\varepsilon}{\varepsilon_{\max }}=-\frac{y / \rho}{c / \rho} \\
\varepsilon=-\left(\frac{y}{c}\right) \varepsilon_{\max }
\end{gathered}
\]</span></p>
<p>Assuming that the material behaves in a linearly elastic manner, we use Hooke’s law, <span class="math inline">\(\sigma = E \epsilon\)</span>, to rewrite the strain relationship into a relationship of stresses.</p>
<p><span class="math display">\[
\sigma=-\left(\frac{y}{c}\right) \sigma_{\max }
\]</span></p>
<p>Therefore, similar to the variation in normal strain, normal stress, σ, will fluctuate from zero at the neutral surface to a maximum value, σ<sub>max</sub>, at a distance c from the neutral surface as shown in <a href="#fig-9.7" class="quarto-xref">Figure&nbsp;<span>9.7</span></a>.</p>
<div id="fig-9.7" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A horizontal rectangular cross section is shown with x- and y-axes. The x-axis is horizontal and aligned with the dashed neutral surface, which passes through the middle of the section. Arrows in the top half point left, representing compressive stresses, while arrows in the bottom half point right, representing tensile stresses. The arrows are longest at the outer edges and decrease linearly toward the neutral surface. A vertical double-headed arrow labeled c marks the distance from the neutral surface to the outermost fiber." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/chapter 9 figure updates/9.7 new.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A horizontal rectangular cross section is shown with x- and y-axes. The x-axis is horizontal and aligned with the dashed neutral surface, which passes through the middle of the section. Arrows in the top half point left, representing compressive stresses, while arrows in the bottom half point right, representing tensile stresses. The arrows are longest at the outer edges and decrease linearly toward the neutral surface. A vertical double-headed arrow labeled c marks the distance from the neutral surface to the outermost fiber." width="429">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.7: Bending stress variation
</figcaption>
</figure>
</div>
<p>For us to determine the position of the neutral surface, the resultant force generated by the stress distribution across the cross-sectional area must be equal to zero.</p>
<p><span class="math display">\[
0=\int_A F_{resultant}=\int_A \sigma d A
\]</span></p>
<p>We can now substitute the previous relationship between stress and distance from neutral axis.</p>
<p><span class="math display">\[
\begin{aligned}
&amp; 0=\int_A-\left(\frac{y}{c}\right) \sigma_{\max } d A \\
&amp; 0=-\frac{\sigma_{\max }}{c} \int_A y d A
\end{aligned}
\]</span></p>
<p>Since <span class="math inline">\(-\frac{\sigma_{\max }}{c}\)</span> does not equal zero, what remains is</p>
<p><span class="math display">\[
0=\int_A y d A
\]</span></p>
<p>This integral represents the first moment of area, as discussed in <a href="Chapter 8.html#sec-8.1" class="quarto-xref"><span>Section 8.1</span></a>. This equation indicates that the first moment of the cross-section about its neutral axis must be zero. Recall that the location of the centroid was determined by <span class="math inline">\(\bar{y}=\frac{\int_A y d A}{A}\)</span>. Consequently, for a member experiencing pure bending and as long as the stresses remain within the elastic range, the neutral axis traverses through the centroid of the section because <span class="math inline">\(\bar{y}\)</span> (the distance from the neutral axis to the centroid) is zero.</p>
<p>The stress in the beam can be ascertained by setting the moment M equal to the moment produced by the stress distribution around the neutral axis.</p>
<p><span class="math display">\[
d M=y d F
\]</span></p>
<p>Since</p>
<p><span class="math display">\[
d F=\sigma d A\text{ ,}
\]</span></p>
<p>we can write</p>
<p><span class="math display">\[
\begin{gathered}
M=\int_A y d F=\int_A y(\sigma d A)=\int_A y\left(-\frac{y}{c} \sigma_{\max }\right) d A \\
M=\frac{\sigma_{\max }}{c} \int_A y^2 d A
\end{gathered}
\]</span></p>
<p>Note that the integral, <span class="math inline">\(\int_A y^2 d A\)</span>, represents the second moment of area, or the moment of inertia, of the cross-sectional area about the neutral axis. Here second moment of area is denoted with I, as in <a href="Chapter 8.html#sec-8.2" class="quarto-xref"><span>Section 8.2</span></a>.</p>
<p>Rearranging the previous equation to obtain the flexure formula yields</p>
<p><span id="eq-9.1"><span class="math display">\[
\boxed{\sigma_{\max }=\frac{M c}{I}}\text{ ,}
\tag{9.1}\]</span></span></p>
<div class="line-block">where<br>
<em>σ<sub>max</sub> = Maximum bending stress in the beam; note that a complete description includes magnitude, units, and tension or compression [Pa, psi]</em><br>
<em>M = Internal bending moment calculated about the neutral axis of the cross section, determined from method of sections or shear and moment diagrams [N·m, lb·in.]</em><br>
<em>c = Perpendicular distance from the neutral axis to the point farthest from the neutral axis [m, in.]</em><br>
<em>I = Second moment of area about the neutral axis [m<sup>4</sup>, in.<sup>4</sup>]</em></div>
<p>Previous derivation has shown that</p>
<p><span class="math display">\[
\sigma=-\left(\frac{y}{c}\right) \sigma_{\max }
\]</span></p>
<p>This can be rearranged to provide the following relationship:</p>
<p><span class="math display">\[
\frac{\sigma_{\max }}{c}=-\frac{\sigma}{y}
\]</span></p>
<p>We can determine a similar flexure formula to calculate the bending stress at any point along the cross section.</p>
<p><span id="eq-9.2"><span class="math display">\[
\boxed{\sigma=-\frac{M y}{I}}\text{ ,}
\tag{9.2}\]</span></span></p>
<div class="line-block">where<br>
<em>σ = Bending stress [Pa, psi]</em><br>
<em>M = Internal moment calculated about the neutral axis of the cross section [N·m, lb·in.]</em><br>
<em>y = Perpendicular distance from the neutral axis to the point of interest [m, in.]</em><br>
<em>I = Second moment of area about the neutral axis [m<sup>4</sup>, in.<sup>4</sup>]</em></div>
<p>As emphasized in <a href="Chapter 2.html" class="quarto-xref"><span>Chapter 2</span></a>, when reporting normal stress engineers must indicate whether that stress is in tension or compression. The derivation for <a href="#eq-9.2" class="quarto-xref">Equation&nbsp;<span>9.2</span></a> used a beam bending concave upward. In <a href="Chapter 7.html" class="quarto-xref"><span>Chapter 7</span></a> we indicated that this type of moment was considered positive. This leads to compression above the neutral axis and tension below. The inverse is true when the beam is subjected to negative bending moment as shown in <a href="#fig-9.8" class="quarto-xref">Figure&nbsp;<span>9.8</span></a>.</p>
<div id="fig-9.8" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two bending diagrams are shown side by side. The left diagram illustrates a positive moment: the beam bends concave up, with compression at the top and tension at the bottom. Curved arrows at the ends indicate upward bending, clockwise on the left and counterclockwise on the right. The right diagram illustrates a negative moment: the beam bends concave down, with tension at the top and compression at the bottom. Curved arrows at the ends indicate downward bending, counterclockwise on the left and clockwise on the right. In both diagrams, a dashed line through the mid-height marks the neutral axis." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/CH9 PNGs/Figure 9.9.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Two bending diagrams are shown side by side. The left diagram illustrates a positive moment: the beam bends concave up, with compression at the top and tension at the bottom. Curved arrows at the ends indicate upward bending, clockwise on the left and counterclockwise on the right. The right diagram illustrates a negative moment: the beam bends concave down, with tension at the top and compression at the bottom. Curved arrows at the ends indicate downward bending, counterclockwise on the left and clockwise on the right. In both diagrams, a dashed line through the mid-height marks the neutral axis." width="499">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.8: Bending stress sign convention
</figcaption>
</figure>
</div>
<p><a href="#exm-9.2" class="quarto-xref">Example&nbsp;<span>9.2</span></a> and <a href="#exm-9.3" class="quarto-xref">Example&nbsp;<span>9.3</span></a> demonstrate the calculation of bending stresses at various points on a cross-section.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example 9.1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="exm-9.1" class="theorem example">
<p><span class="theorem-title"><strong>Example 9.1</strong></span> &nbsp;</p>
<p>
</p>
<p>For the timber beam shown, calculate the normal stress at the top, bottom, and at point A when the beam experiences a +30 kN·m moment.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/chapter 9 figure updates/example 9.1 new part 1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Vertical rectangular cross section with overall dimensions labeled. The section is 300 mm tall and 80 mm wide. Point A is marked 100 mm below the top edge." width="243"></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Since we are asked to find the bending stress, let’s look at the bending stress formula.</p>
<p><span class="math display">\[
{\sigma=-\frac{M y}{I}}
\]</span></p>
<p>Start with the internal moment, which is a given in the problem statement to be +30 kN·m. Positive moment indicates that the beam is bending concave up, with compression above the neutral axis and tension below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/chapter 9 figure updates/example 9.1 new part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Curved beam segment with a thick blue shaded cross section. The beam bends concave upward, with the inner curve labeled Compression and the outer curve labeled Tension. The diagram illustrates positive bending, where the top fibers are in compression and the bottom fibers are in tension." width="269"></p>
</figure>
</div>
<p>The value of <em>y</em> is the perpendicular distance from the neutral axis to the point of interest. This problem has three points of interest so it has three different y values—one each for the top, the bottom, and point A.</p>
<p>Next determine the beam properties, which are the centroid and the second moment of area. Since the cross section is a rectangle, the centroid is located at the midpoint of the beam’s height. You can then use the formula for second moment of area for a rectangle from <a href="Appendix E.html" class="quarto-xref"><span>Appendix E</span></a>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/chapter 9 figure updates/example 9.1 new part 3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Vertical rectangular cross section with overall dimensions labeled. The section is 300 mm tall and 80 mm wide. Point A is marked 100 mm below the top edge. A vertical dimension of 50 mm is shown from Point A down to the centroid, and another dimension of 150 mm is marked from the centroid to the bottom edge." width="273"></p>
</figure>
</div>
<p><span class="math display">\[
\begin{gathered}
I_x=\frac{1}{12}(0.080m)(0.3m)^3 \\
I_x=1.8*10^{-4}*m^4
\end{gathered}
\]</span></p>
<p>Now calculate stress at each of the three points requested. Start with the top.</p>
<p><span class="math display">\[
\sigma_{top}=-\frac{(30*10^3~Nm)(0.15~m)}{1.8*10^{-4}~m^4}=-25~MPa
\]</span></p>
<p>A complete answer must include magnitude, units, and tension or compression. The magnitude is 25, the units will be MPa. To determine the tension or compression look at the sign of the internal moment and where along the section you are calculating the bending stress. In this example the moment is positive and we calculated the stress at the top of the section.</p>
<p>The calculation shows the bending stress to be in compression.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/chapter 9 figure updates/example 9.1 new part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Curved beam segment with a thick blue shaded cross section. The beam bends concave upward, with the inner curve labeled Compression and the outer curve labeled Tension. The diagram illustrates positive bending, where the top fibers are in compression and the bottom fibers are in tension." width="265"></p>
</figure>
</div>
<p><span class="math display">\[
\sigma_{top}=25~MPa~~(C)
\]</span></p>
<p>Note that as long as care is taken to use the correct signs for M and y (both positive in this case), the answer will come out with the correct sign (negative in this case, which indicates compression).</p>
<p>Next calculate the normal stress at the bottom of the beam. In this case all the values (M, y, and I) are the same, so the magnitude of the stress is the same (25 MPa). What changes is the type of stress (tension or compression). Since in this example the moment is positive and we calculated the stress at the bottom of the beam, the stress will be in tension.</p>
<p><span class="math display">\[
\begin{gathered}
\sigma_{btm}=-\frac{(30*10^3~Nm)(-0.15~m)}{1.8*10^{-4}~m^4}=25~MPa\\
\\
\sigma_{btm}=25~MPa~~(T)
\end{gathered}
\]</span></p>
<p>Finally, calculate the stress at point A, which is located 100 mm from the top of the section. The y value measures from the neutral axis (centroid), so use y = 50 mm.</p>
<p><span class="math display">\[
\sigma_{A}=\frac{(30*10^3~Nm)(0.05~m)}{1.8*10^{-4}~m^4}=8.33~MPa
\]</span></p>
<p>As before, evaluate whether the stress is in tension or compression. Since point A is above the neutral axis and the moment is positive, the stress at point A will be in compression.</p>
<p><span class="math display">\[
\sigma_A=8.33~MPa~~(C)
\]</span></p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example 9.2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="exm-9.2" class="theorem example">
<p><span class="theorem-title"><strong>Example 9.2</strong></span> &nbsp;</p>
<p>
</p>
<p>A beam with the shown cross section is subjected to a positive moment of 50 kip·in.</p>
<p>Calculate the normal stress at the top, bottom, and interface between flange and web.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.1 part 1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="T-shaped composite section with overall dimensions. The top flange is horizontal, 9 inches wide and 1.5 inches tall. The vertical stem is centered beneath the flange, 3 inches wide and 4.5 inches tall. The entire section is shaded gray to indicate it is solid." width="292"></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Start with the internal moment, which is given in the problem statement as +50 kip·in. The positive moment indicates that the beam is bending concave up, with compression above the neutral axis and tension below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.1 part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Curved beam segment with a thick blue shaded cross section. The beam bends concave upward, with the inner curve labeled Compression and the outer curve labeled Tension. The diagram illustrates positive bending, where the top fibers are in compression and the bottom fibers are in tension." width="267"></p>
</figure>
</div>
<p>Next determine the beam properties, which are the centroid and the second moment of area. Since this is not a standard shape and the shape is not symmetric in the y direction, you will need to calculate this by hand. <a href="Chapter 8.html#exm-8.1" class="quarto-xref">Example&nbsp;<span>8.1</span></a> and <a href="Chapter 8.html#exm-8.4" class="quarto-xref">Example&nbsp;<span>8.4</span></a> cover this shape in detail.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.1 part 3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Same T-shaped composite section divided into two rectangles labeled 1 and 2. Rectangle 1 is the vertical stem, and Rectangle 2 is the horizontal flange. A black point labeled RP marks the reference point at the bottom left corner of the stem. Dimensions remain the same: the stem is 3 inches wide and 4.5 inches tall, and the flange is 9 inches wide and 1.5 inches tall." width="270"></p>
</figure>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Shape</th>
<th><span class="math inline">\(A {~(in.^2})\)</span></th>
<th><span class="math inline">\(\bar{y}{~(in.})\)</span></th>
<th><span class="math inline">\(A\bar{y}{~(in.^3})\)</span></th>
<th><span class="math inline">\(I_x{~(in.^4})\)</span></th>
<th><span class="math inline">\(d_y{~(in.})\)</span></th>
<th><span class="math inline">\(I_x+Ad_y^2{~(in.^4})\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>13.5</td>
<td>2.25</td>
<td>30.375</td>
<td>22.78125</td>
<td>1.5</td>
<td>53.15625</td>
</tr>
<tr class="even">
<td>2</td>
<td>13.5</td>
<td>5.25</td>
<td>70.875</td>
<td>2.53125</td>
<td>1.5</td>
<td>32.90625</td>
</tr>
<tr class="odd">
<td></td>
<td><span class="math inline">\(\sum A\)</span> = 27</td>
<td></td>
<td><span class="math inline">\(\sum A\bar{y}\)</span> = 101.25</td>
<td></td>
<td></td>
<td><span class="math inline">\(\sum I_{x}\)</span> = 86.0625</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\begin{aligned}
\bar{Y}=\frac{101.25{~in.^3}}{27{~in.^2}} &amp; =3.75{~in.}~~\text{from bottom} \\
&amp; =2.25{~in.}~~\text{from top} \\
\end{aligned}
\]</span></p>
<p>This problem has three parts that change the y value. Begin by calculating the stress at the top of the section, using the flexure formula.</p>
<p><span class="math display">\[
\sigma_{t o p}=-\frac{M y}{I}
\]</span></p>
<p>Before plugging in our values, ensure that the units are consistent.</p>
<ul>
<li><p><span class="math inline">\(M = 50{~kip}\cdot{in.}\)</span></p></li>
<li><p><span class="math inline">\(y = 2.25{~in.}\)</span></p></li>
<li><p><span class="math inline">\(I = 86.0625{~in.^4}\)</span></p></li>
</ul>
<p>Since all units are in kips and inches, plug them into the flexure formula.</p>
<p><span class="math display">\[
\sigma_{top}=-\frac{(50{~kip}\cdot{in.})(2.25{~in.})}{86.0625{~in.}^4}=-1.31{~ksi}
\]</span></p>
<p>For a complete answer include magnitude, units, and tension or compression. The magnitude is 1.31, the units will be kips/in<sup>2</sup> or ksi. To determine the tension or compression look at the sign of the internal moment and where along the section you are calculating the bending stress. In this example the moment is positive, so calculate the stress at the top of the section. The answer will show the bending stress to be in compression.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.1 part 4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Curved beam segment with a thick blue shaded cross section. The beam bends concave upward, with the inner curve labeled Compression and the outer curve labeled Tension. The diagram illustrates positive bending, where the top fibers are in compression and the bottom fibers are in tension." width="268"></p>
</figure>
</div>
<p><span class="math display">\[
\sigma_{top}=1.31{~ksi}~(C)
\]</span></p>
<p>Note that as long as care is taken to use the correct signs for M and y (both positive in this case), the answer will come out with the correct sign (negative in this case, which indicates compression).</p>
<p>Now calculate the normal stress at the bottom of the beam. The only quantity that changes is the y value, so now use the distance from the neutral axis to the bottom of the beam (3.75 in.).</p>
<p><span class="math display">\[
\sigma_{btm}=-\frac{(50{~kip}\cdot{in.})(-3.75{~in.})}{86.0625{~in.}^4}=2.18{~ksi}
\]</span></p>
<p>Because the moment is positive, the beam bends concave up. Anything below the neutral axis is in tension.</p>
<p><span class="math display">\[
\sigma_{btm}=2.18{~ksi}~(T)
\]</span></p>
<p>This again works mathematically as long as you use the correct positive sign for the M and negative sign for y (since the point of interest is below the neutral axis). The answer shows this stress to be positive, indicating tension and matching expectation.</p>
<p>Finally, calculate the normal stress at the junction of the flange and the web. To do this find the distance from the neutral axis to the flange web junction.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.1 part 5.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="T-shaped composite section with overall dimensions. The top flange is 9 inches wide and 1.5 inches tall. The vertical stem, centered beneath the flange, is 3 inches wide and 4.5 inches tall." width="324"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.1 part 6.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Same as image above, except this one isolates the vertical stem as a rectangle. A horizontal dashed line labeled Neutral axis intersects the rectangle, located 0.75 inches below the top edge, calculated as 4.5 minus 3.75. The distance from the bottom of the stem to the neutral axis is labeled as 3.75 inches." width="449"></p>
</figure>
</div>
<p><span class="math display">\[
\sigma_{F / w}=-\frac{(50{~kip}\cdot{in.})(0.75{~in.})}{86.0625{~in.}^4}=-0.436{~ksi}
\]</span></p>
<p>Since the flange web junction is above the neutral axis and the beam is subjected to positive moment, the bending stress will be in compression.</p>
<p><span class="math display">\[
\sigma_{F/w}=0.436{~ksi}~(C)
\]</span></p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div id="example-9.2" class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example 9.3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="exm-9.3" class="theorem example">
<p><span class="theorem-title"><strong>Example 9.3</strong></span> &nbsp;</p>
<p>
</p>
<p>Calculate the maximum tensile and maximum compressive bending stress in the beam shown.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-1391458310.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A simply supported beam with a triangular pin support at point A on the far left and a circular roller support at point B, located 10 meters from A. A uniformly distributed load of 4 kilonewtons per meter is applied over a 6-meter span, starting 2 meters to the right of A and ending 2 meters before B. At the same location, a concentrated 10 kilonewton downward force is applied. Another 15 kilonewton downward force is applied at the far right end of the beam, 12 meters from A and 2 meters to the right of B." width="364"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-1969407560.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A symmetric I-shaped cross section, symmetric about the vertical y-axis but not the horizontal x-axis. The top flange is 180 mm wide and 40 mm high. The central web is 20 mm wide and 140 mm high. The bottom flange is 100 mm wide and 40 mm high. All components are vertically aligned and centered along the y-axis. A coordinate system is drawn to the right, with the x-axis pointing horizontally and the y-axis pointing upward." width="370"></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The first step is to find the beam’s internal forces so that we can find the maximum positive and negative moments. The best way to do this is to draw the moment diagram, as detailed in <a href="Chapter 7.html#exm-7.3" class="quarto-xref">Example&nbsp;<span>7.3</span></a>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-191172276.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Top: Free body diagram of a simply supported beam. At point A on the far left, the pin support provides an 11 kilonewton upward reaction. At point B, a roller support 10 meters from A provides a 38 kilonewton upward reaction. A uniformly distributed load of 4 kilonewtons per meter is applied over a 6-meter span, starting 2 meters to the right of A and ending 2 meters before B. At the same location, a 10 kilonewton concentrated downward force is applied. At the far right end, 12 meters from A and 2 meters beyond B, a 15 kilonewton downward force is applied. Bottom: A bending moment diagram shaded in orange with a parabolic curve. Key values are marked: zero at point A, 22 kilonewton-meters at 2 meters, a maximum of 37.125 kilonewton-meters at approximately 4.75 meters, 16 kilonewton-meters at 8 meters, -30 kilonewton-meters at point B (10 meters), and zero again at the far right end." width="366"></p>
</figure>
</div>
<p>Note that the maximum positive moment is 37.125 kN·m and the maximum negative moment is 30 kN·m.</p>
<p>Next determine the beam’s geometric properties, which are the centroid and the second moment of area. Since this is not a standard shape and the shape is not symmetric in the y direction, calculate this by hand. <a href="Chapter 8.html#exm-8.2" class="quarto-xref">Example&nbsp;<span>8.2</span></a> and <a href="Chapter 8.html#exm-8.5" class="quarto-xref">Example&nbsp;<span>8.5</span></a> covered this shape in detail.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.2 part 5.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A symmetric I-shaped cross section, symmetric about the vertical y-axis but not the horizontal x-axis. The top flange is 180 mm wide and 40 mm high. The central web is 20 mm wide and 140 mm high. The bottom flange is 100 mm wide and 40 mm high. All components are vertically aligned and centered along the y-axis. A coordinate system is drawn to the right, with the x-axis pointing horizontally and the y-axis pointing upward." width="360"></p>
</figure>
</div>
<p>Find the centroid (<span class="math inline">\(\bar{x} = 0\)</span> due to symmetry).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 26%">
<col style="width: 24%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th>Shape</th>
<th><span class="math inline">\(A{~(mm}^2)\)</span></th>
<th><span class="math inline">\(\bar{y}{~(mm})\)</span></th>
<th><span class="math inline">\(A\bar{y}{~(mm^3})\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>4,000</td>
<td>20</td>
<td>80,000</td>
</tr>
<tr class="even">
<td>2</td>
<td>2,800</td>
<td>110</td>
<td>308,000</td>
</tr>
<tr class="odd">
<td>3</td>
<td>7,200</td>
<td>200</td>
<td>1,440,000</td>
</tr>
<tr class="even">
<td></td>
<td><span class="math inline">\(\sum A\)</span> = 14,000</td>
<td></td>
<td><span class="math inline">\(\sum A\bar{y}\)</span> = 1,828,000</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\bar{Y}=130.6{~mm}~~\text{from bottom}\)</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Shape</th>
<th><span class="math inline">\(I_x{~(mm^4})\)</span></th>
<th><span class="math inline">\(d_y{~(mm})\)</span></th>
<th><span class="math inline">\(I_x+Ad_y^2{~(mm^4)}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>533,333</td>
<td>110.57</td>
<td>49,436,233</td>
</tr>
<tr class="even">
<td>2</td>
<td>4,573,333</td>
<td>20.57</td>
<td>5,758,083</td>
</tr>
<tr class="odd">
<td>3</td>
<td>960,000</td>
<td>69.43</td>
<td>35,667,779</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td>I<sub>x</sub> = 90,862,095 mm<sup>4</sup></td>
</tr>
</tbody>
</table>
<p>The positive bending moment will cause compression at the top of the cross-section and tension at the bottom. The negative bending moment will cause tension at the top and compression at the bottom. It’s not obvious by inspection which of these two tensile stresses will be larger, nor which of the two compressive stresses will be larger. We should calculate all four to compare.</p>
<p>Before plugging in the values, ensure that the units are consistent, so change everything to Newtons and meters.</p>
<ul>
<li><p>M<sub>pos</sub> = 37.125 kN·m = 37.125 x 10<sup>3</sup> N·m</p></li>
<li><p>M<sub>neg</sub> = 30 kN·m = 30 x 10<sup>3</sup> N·m</p></li>
<li><p>y<sub>top</sub> = 89.43 mm = 0.08943 m</p></li>
<li><p>y<sub>btm</sub> = 130.57 mm = 0.13057 m</p></li>
<li><p>I<sub>x</sub> = 90,862,095 mm<sup>4</sup> = 90.862095 x 10<sup>-6</sup> m<sup>4</sup></p></li>
</ul>
<p>Start by calculating the section’s top and bottom stress from the maximum positive moment, using the flexure formula.</p>
<p><span class="math display">\[ \sigma=-\frac{M y}{I} \]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.2 part 6.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Curved beam segment with a thick blue shaded cross section. The beam bends concave upward, with the inner curve labeled Compression and the outer curve labeled Tension. The diagram illustrates positive bending, where the top fibers are in compression and the bottom fibers are in tension." width="278"></p>
</figure>
</div>
<p><span class="math display">\[ \sigma_{top/pos}=-\frac{\left(37.125 \times 10^3{~N}\cdot{m}\right)(0.0893 {~m})}{90.86 \times 10^{-6}{~m}^4}=-36.49{~MPa~(C)} \]</span></p>
<p><span class="math display">\[ \sigma_{btm/pos}=-\frac{\left(37.125\times10^3{~N}\cdot{m}\right)(-0.13057{~m})}{90.86 \times 10^{-6}{~m}^4}=53.35{~MPa}{~(T)} \]</span></p>
<p>Now do something similar for the maximum negative bending stress.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.2 part 7.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Curved beam segment with a thick blue shaded cross section. The beam bends concave downward, with the top curve labeled Compression and the bottom curve labeled Tension. The diagram illustrates negative bending, where the top fibers are in compression and the bottom fibers are in tension." width="262"></p>
</figure>
</div>
<p><span class="math display">\[ \sigma_{top/neg}=-\frac{\left(-30 \times 10^3{~N}\cdot{m}\right)(0.0893{~m})}{90.86 \times 10^{-6}{~m}^4}=29.48{~MPa~(T)} \]</span></p>
<p><span class="math display">\[ \sigma_{btm/neg}=-\frac{\left(-30 \times 10^3 \mathrm{~N}\cdot{m}\right)(-0.13057{~m})}{90.86 \times 10^{-6}{~m}^4}=-43.11{~MPa}~{(C)} \]</span></p>
<p>The overall maximum tensile stress for this beam occurs at the bottom of the section due to positive moment, 53.35 MPa (T). The overall maximum compressive stress (43.11 MPa (C)) also occurs at the bottom of the section in a different part of the beam but is due to the negative moment.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>For many situations the overall largest stress would be sufficient. However, some materials behave differently depending on whether they are subjected to tensile or compressive stress. Concrete is a good example of this, as it’s relatively strong against compressive stresses but very weak against tensile stresses. Steel rebar is placed inside concrete members to support the tensile stresses as shown in <a href="#fig-9.9" class="quarto-xref">Figure&nbsp;<span>9.9</span></a>. At this point in your engineering career it is good practice to report both the maximum tensile and compressive stresses at each critical point on the beam.</p>
<div id="fig-9.9" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A close-up view of a prestressed concrete girder under construction is shown. Multiple steel tendons extend horizontally from the end of the beam, protruding from anchor heads embedded in the girder. The tendons are arranged in an organized pattern and will eventually be tensioned and anchored to provide prestressing force." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/figure 9.10 (needs replacement).jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A close-up view of a prestressed concrete girder under construction is shown. Multiple steel tendons extend horizontally from the end of the beam, protruding from anchor heads embedded in the girder. The tendons are arranged in an organized pattern and will eventually be tensioned and anchored to provide prestressing force." width="493">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.9: The end of the prestressed concrete beam showing the prestressing steel and rebar
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Step-by-Step: Calculating Bending Stress
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Determine the <strong>internal moment</strong> at the point where you want to calculate the bending stress. If you know the point along the length of the beam that you are investigating, you can cut a section and apply equilibrium equations to determine this moment. If you need to find the maximum bending stress, then draw the moment diagram to find the maximum internal moment (<a href="Chapter 7.html" class="quarto-xref"><span>Chapter 7</span></a> reviews this).</li>
<li>Determine the section properties of the beam. This will require knowing the location of the centroid, neutral axis, and second moment of area. (See <a href="Chapter 8.html" class="quarto-xref"><span>Chapter 8</span></a> for a review or <a href="Appendix E.html" class="quarto-xref"><span>Appendix E</span></a> for a table listing I values for selected common shapes.)</li>
<li>Identify the specific location on the section for which you are computing the normal stress, y (or c, if you are calculating the maximum normal stress.)</li>
<li>Ensure that the units of M, I, and y (or c) are consistent, then use one of the flexure formulas to calculate bending stress. Ensure that the result indicates the magnitude, units, and tension or compression.</li>
</ol>
</div>
</div>
</details>
</section>
<section id="sec-9.2" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="sec-9.2"><span class="header-section-number">9.2</span> Beam Design for Bending</h2>
<details>
<summary>
Click to expand
</summary>
<p>Frequently beam design is governed by the bending moment. This section leverages your understanding of bending stress to design two common categories of beams capable of withstanding their applied internal moments. This section starts with rolled steel beams of varying cross sections. <a href="Appendix A.html" class="quarto-xref"><span>Appendix A</span></a> provides a sampling of these standard shapes. Then follows a discussion of rectangular cross-sections, which are common for timber beams.</p>
<p>A safe design requires that the allowable stress of the material used is greater than the stress due to the loading. The flexure equation for maximum bending stress, <span class="math inline">\(\sigma_m=\frac{M_{\max } c}{I}\)</span>, has four variables: σ<sub>m</sub>, M<sub>max</sub>, c, and I. We’ll start with the allowable stress of the material, σ<sub>all</sub>, and use the |M<sub>max</sub>| derived from the loading condition. What is left are section properties, I, and c.&nbsp;For standard shapes these are combined into one variable, section modulus (S).</p>
<p><span id="eq-9.3"><span class="math display">\[
\boxed{S=\frac{I}{c}}
\tag{9.3}\]</span></span></p>
<p>We can substitute this value into the flexure formula and rearrange for S<sub>min</sub>, which is the minimum allowable value of the section modulus for the beam.</p>
<p><span id="eq-9.4"><span class="math display">\[
\boxed{S_{min}=\frac{\left|M_{\max}\right|}{\sigma_{allow}}}\text{ ,}
\tag{9.4}\]</span></span></p>
<div class="line-block">where<br>
<em>Smin = Minimum required section modulus for a beam to resist the bending stress [m<sup>3</sup>, in.<sup>3</sup>]</em><br>
<em>|M<sub>max</sub>| = Magnitude of the maximum internal bending moment [N·m, lb·in.]</em><br>
<em>𝜎<sub>allow</sub> = Maximum allowable stress for the beam [Pa, psi]</em></div>
<section id="design-of-standard-steel-sections" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="design-of-standard-steel-sections"><span class="header-section-number">9.2.1</span> Design of Standard Steel Sections</h3>
<p>As long as the beam is designed such that its section modulus is larger than S<sub>min</sub>, the beam is guaranteed not to fail due to bending stress. Rolled steel beams tend to have relatively complex cross-sections with multiple dimensions that can be varied to alter a beam’s section modulus and therefore its resistance to bending stress. Designing each dimension individually would be time consuming and it would be costly to manufacture a unique beam for every loading condition.</p>
<p>Instead, beams are mass produced in standard sizes and engineers simply select the most appropriate beam for their specific need. Thus many safe standard steel shapes are available to satisfy this equation. Engineering is determining which of the shapes that work you will use. Often you will need to consider many criteria.</p>
<p>In this section we use cost to determine the shape. Steel beams are priced by their weight, and the higher the weight, the more expensive. To choose the most economical shape, we have selected the shape with the smallest weight (i.e., smallest cross-sectional area).</p>
<p>Basic structural steel shapes have standardized cross sectional dimensions. W shapes (standing for wide flange) are often used for beam design because they have an efficient cross section. <a href="#fig-9.10" class="quarto-xref">Figure&nbsp;<span>9.10</span></a> is a sample of the beam table in <a href="Appendix A.html" class="quarto-xref"><span>Appendix A</span></a>.</p>
<div id="fig-9.10" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Cross-sectional view of a wide-flange I-beam with key geometric parameters labeled. The total height is marked d, the flange thickness is t sub f, the flange width is b sub f, and the web thickness is t sub w. The horizontal centroidal axis is labeled x, and the vertical symmetry axis is labeled y. Below the figure, a table lists dimensions, area, moments of inertia about the x- and y-axes, and radii of gyration r sub x and r sub y for different beam designations, including W40 × 431, W40 × 297, and W40 × 264." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Updated appendices figures/figure 9.10.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Cross-sectional view of a wide-flange I-beam with key geometric parameters labeled. The total height is marked d, the flange thickness is t sub f, the flange width is b sub f, and the web thickness is t sub w. The horizontal centroidal axis is labeled x, and the vertical symmetry axis is labeled y. Below the figure, a table lists dimensions, area, moments of inertia about the x- and y-axes, and radii of gyration r sub x and r sub y for different beam designations, including W40 × 431, W40 × 297, and W40 × 264.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.10: Portion of the W section table from <a href="Appendix A.html" class="quarto-xref"><span>Appendix A</span></a>
</figcaption>
</figure>
</div>
<p>Each beam has a designation that quickly gives us information about the section (see <a href="#fig-9.11" class="quarto-xref">Figure&nbsp;<span>9.11</span></a>).</p>
<div id="fig-9.11" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Wide-flange steel beam designation labeled ‘W12 × 96.’ The label is divided into three annotated parts: W indicates the shape type, a wide-flange section; 12 gives the approximate depth in inches; and 96 specifies the weight in pounds per foot. Bracketed annotations with descriptions are placed directly below each part of the designation." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/CH9 PNGs/Figure 9.12.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Wide-flange steel beam designation labeled ‘W12 × 96.’ The label is divided into three annotated parts: W indicates the shape type, a wide-flange section; 12 gives the approximate depth in inches; and 96 specifies the weight in pounds per foot. Bracketed annotations with descriptions are placed directly below each part of the designation." width="368">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.11: Description of the shape designation in US customary units
</figcaption>
</figure>
</div>
<p>Notice in the sample beam section table in <a href="#fig-9.10" class="quarto-xref">Figure&nbsp;<span>9.10</span></a> that all are W shapes and grouped by approximate height (first number). Within each height grouping the shapes are arranged from lightest to heaviest (second number) when going from the bottom to top of the height grouping. Given for each standard shape in this table are the cross-sectional area, depth (height), flange and web dimensions, second moment of area in the x and y directions, section modulus in the x and y direction, and radius of gyration in the x and y directions (last is a geometric property related to buckling, used in <a href="Chapter 15.html" class="quarto-xref"><span>Chapter 15</span></a>).</p>
<p>In certain instances the selection of a section might be constrained by such factors as the permissible depth of the cross-section or the allowable deflection of the beam. Here the discussion is limited to materials that behave the same in tension and compression. If this is not the case (e.g., when using concrete), then you may need to check multiple points along the length of the beam. Additionally, if the section is not symmetric about the neutral axis, the maximum tensile and compressive stresses may not occur at the chosen place on the beam. Note that this procedure considers only bending stresses. Although bending stresses do control the design of most beams, there are instances where shear or deflection will be in control. <a href="Chapter 11.html" class="quarto-xref"><span>Chapter 11</span></a> discusses this topic further.</p>
<p><a href="#exm-9.3" class="quarto-xref">Example&nbsp;<span>9.3</span></a> designs a wide-flange beam to resist bending stress.</p>
<div id="example-9.3" class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example 9.4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="exm-9.4" class="theorem example">
<p><span class="theorem-title"><strong>Example 9.4</strong></span> &nbsp;</p>
<p>
</p>
<p>Knowing that the allowable normal stress for the steel used is 24 ksi, select the most economical wide-flange beam to support the loading shown.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/chapter 9 figure updates/example 9.3 new part 1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A simply supported beam spans horizontally from point A on the left (with a triangular support indicating a pinned support) to point B on the right (with a circular support indicating a roller). The beam is subjected to three loads: a concentrated vertical downward force of 8 kips applied 5 feet from point A, a concentrated vertical upward force of 5 kips applied 11 feet from point A, and a uniformly distributed load of 3 kips per foot applied over the final 6 feet of the span up to point B. The span is divided into segments labeled 5 ft, 6 ft, 3 ft, and 6 ft from left to right." width="361"></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The first step is to find the internal forces in the beam. We’ll start by calculating the reactions.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.3 part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Simply supported beam with supports at points A (pin) and B (roller), spanning a total of 20 feet. Three vertical loads act on the beam: an 8 kip downward point load located 5 feet from point A, a 5 kip upward point load located 11 feet from point A, and a uniformly distributed load of 3 kips per foot applied over the final 6 feet of the span (from 14 to 20 feet). Reaction forces are labeled at each support: A sub x pointing left (horizontal), A sub y pointing up (vertical), and B sub y also pointing up. A horizontal dimension line below the beam divides the span into segments of 5 ft, 6 ft, 3 ft, and 6 ft, corresponding to the distances between the loads and supports." width="365"></p>
</figure>
</div>
<p><span class="math display">\[
\begin{aligned}
\sum&amp; F_x =A_x =0\\
\sum&amp; M_A =-8{~kips}(5{~ft})+5{~kips}(11{~ft})-(3\frac{kips}{ft}*6{~ft})(17{~ft})+B_y(20{~ft})=0 \\
&amp;B_y =14.55{~kips} \\
\sum&amp; F_y=A_y-8{~kips}+5{~kips}-(3\frac{kips}{ft})*6{~ft})+14.55{~kips}=0 \\
&amp;A_y=6.45{~kips}
\end{aligned}
\]</span></p>
<p>Now that we have the reactions, we can build the shear diagram.</p>
<p>Starting on the left side, go up the reaction at support A, 6.45 kips. Continue along the beam following the loads to finish the shear diagram.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/chapter 9 figure updates/example 9.3 new part 1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="The top diagram shows a simply supported beam with a pin support at point A on the left and a roller support at point B on the right, spanning a total length of 20 feet. The beam is subjected to an 8 kip downward point load located 5 feet from A, a 5 kip upward point load located 11 feet from A, and a 3 kip-per-foot uniformly distributed load extending over the final 6 feet of the beam from 14 feet to 20 feet." width="347"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/chapter 9 figure updates/example 9.3 new part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A shear force diagram, starting at 6.45 kips, dropping to -1.55 kips after the 8 kip load, increasing to 3.45 kips after the upward 5 kip load, and decreasing linearly to -14.55 kips at the end due to the distributed load." width="348"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/chapter 9 figure updates/example 9.3 new part 3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A bending moment diagram in kip-feet is shown with a series of plotted points connected by curves, indicating the internal moment response along the span. The values on this moment diagram start at 0, go up to 32.25, down to 22.95, up to 33.3, up to 35.28, and down to 0. The diagrams together illustrate the effect of the applied point loads and distributed load on the internal shear and bending behavior of the beam." width="347"></p>
</figure>
</div>
<p>To build the moment diagram calculate the area under the curve from the shear diagram using geometry. Calculate the area of three rectangles and two triangles.</p>
<p><span class="math display">\[
\begin{aligned}
&amp; A_1=(6.45)(5)=32.25 \\
&amp; A_2=(1.55)(6)=9.3 \\
&amp; A_3=(3.45)(3)=10.35 \\
&amp; \frac{18}{6}=\frac{3.45}{x} \quad\rightarrow\quad x=1.15{~ft,}~~~y=6-1.15=4.85 {~ft} \\
&amp; A_4=\frac{1}{2}(1.15)(3.45)=1.98 \\
&amp; A_5=\frac{1}{2}(4.85)(14.55)=35.28 \\
&amp;
\end{aligned}
\]</span></p>
<p>From the moment diagram see that |M<sub>max</sub>| = 35.28 kip·ft. We will use this value and σ<sub>all</sub> = 24 ksi (given in the problem statement) to calculate the minimum section modulus needed, <em>S<sub>min</sub></em>.</p>
<p><span class="math display">\[
\begin{aligned}
&amp; S_{min}=\frac{|M_{max}|}{\sigma_{allow}} \\
&amp; S_{min}=\frac{(35.28{~kip}\cdot{ft})(12\frac{in.}{ft})}{24{~ksi}} \\
&amp; S_{min}=17.64{~in.}^3
\end{aligned}
\]</span></p>
<p>Now that you know the minimum section modulus needed for this beam, go to the standard beam table in <a href="Appendix A.html" class="quarto-xref"><span>Appendix A</span></a>. Focusing on the S<sub>x</sub> column, start at the bottom of the table to select one shape from each height section that is applicable.</p>
<p>For this beam the following sections will be adequate for bending:</p>
<ul>
<li><p>W8 x 21</p></li>
<li><p>W10 x 19</p></li>
<li><p>W12 x 22</p></li>
<li><p>W14 x 22</p></li>
</ul>
<p>Why not choose any from the W4, W5, and W6 groupings? Because none of these beams have a section modulus greater than 17.64 in<sup>3</sup>. Nor do we continue with groupings greater than W14 because those sections are far larger than what we need, as noted by the weight (second number in the designation).</p>
<p>Now choose the most economical beam by comparing the last number in the designation, which represents the weight per foot of the beam. The most economical section for this material and loading is the W10 x 19. This beam weighs 19 lb/ft and is the lightest of the beams selected.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Step-by-Step: Most Economical Beam Design (standard shapes)
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Establish the allowable stress, σ<sub>all</sub>, value of sigma for the chosen material by referring to a table of material properties or consulting design specifications. Proceed with the following steps, assuming that σ<sub>all</sub> is the same for tension and compression.</li>
<li>Determine the maximum absolute value of the bending moment |M<sub>max</sub>| <strong>i</strong>n the beam by drawing the shear force and bending moment diagrams. (<a href="Chapter 7.html" class="quarto-xref"><span>Chapter 7</span></a> reviews this).</li>
<li>Calculate the minimum allowable value of the section modulus using this equation: <span class="math inline">\(S_{min}=\frac{\left|M_{\max }\right|}{\sigma_{all}}\)</span>.</li>
<li>For a rolled steel beam refer to the relevant table in <a href="Appendix A.html" class="quarto-xref"><span>Appendix A</span></a>. Among the accessible beam sections focus solely on those with a section modulus surpassing the minimum value calculated in step 3, S <strong>≥</strong> S<sub>min</sub>. Start at the bottom of the table and select one beam in each height section (if applicable). Then from this short list choose the section with the smallest weight per unit length, as it represents the most economical option for which S <strong>≥</strong> S<sub>min</sub>. It’s essential to note that this choice may not necessarily correspond to the section with the smallest S value.</li>
</ol>
</div>
</div>
</section>
<section id="design-of-rectangular-sections" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="design-of-rectangular-sections"><span class="header-section-number">9.2.2</span> Design of Rectangular Sections</h3>
<p>Rectangular cross-sections are common for timber beams. Only two dimensions need to be specified, base and height. While there are standard rectangular cross-sections too (e.g., 2” x 4”), we’ll approach the design of rectangular cross-sections by assuming that one dimension scales with the other, and so we need to specify only a single dimension. Rather than select from a list of standard cross-sections, we’ll specify this required dimension exactly.</p>
<p>Calculate the minimum section modulus as before.</p>
<p><span class="math display">\[
S_{min}=\frac{\left|M_{max}\right|}{\sigma_{allow}}
\]</span></p>
<p>Now set this value:</p>
<p><span class="math display">\[
S_{min}=\frac{I}{c}
\]</span></p>
<p>For a rectangle, calculate</p>
<p><span class="math display">\[
\begin{gathered}
I=\frac{b h^3}{12} \\
c=\frac{h}{2}
\end{gathered}
\]</span></p>
<p>So the resulting equation is</p>
<p><span class="math display">\[
S_{min}=\frac{I}{c}=\frac{2 b h^3}{12 h}=\frac{b h^2}{6}
\]</span></p>
<p>Problems will be set up such that there is a relationship between b and h, which leaves only one unknown that can be solved for directly. This will be the minimum acceptable size for this dimension—anything larger than the calculated value will not fail due to bending stress.</p>
<p><a href="#exm-9.4" class="quarto-xref">Example&nbsp;<span>9.4</span></a> designs a wooden beam with a rectangular cross-section to resist bending stress.</p>
<div id="example-9.4" class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example 9.5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="exm-9.5" class="theorem example">
<p><span class="theorem-title"><strong>Example 9.5</strong></span> &nbsp;</p>
<p>
</p>
<p>A simply supported timber beam spans a gap of 10 m. It is subjected to a uniform distributed load w = 15 kN/m as shown. The beam has a rectangular cross-section and will be manufactured such that the height is two times the base.</p>
<p>Determine the minimum acceptable dimensions for the cross-section of this beam if the maximum allowable bending stress of the timber is 12 MPa.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.4 part 1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A simply supported beam is shown with a pin support on the left end and a roller support on the right end, spanning a total of 10 meters. The beam is subjected to a uniformly distributed load of 15 kN/m across the entire span. To the right of the beam, a cross-sectional shape is depicted as a vertical rectangle with width labeled as b and height labeled as h, where h equals 2b." width="335"></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The allowable stress is given as σ<sub>all</sub> = 12 MPa. Determine the magnitude of the maximum internal bending moment by drawing the shear force and bending moment diagrams. Since the loading is symmetric, the total applied load of 15 · 10 = 150 kN will be split evenly between the two supports. The reaction force at each support will be 75 kN.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.4 part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="The top diagram shows a simply supported beam subjected to a uniform distributed load of 15 kN/m across its entire span. The beam has equal vertical reaction forces of 75 kN at both ends. Below the beam, the shear force diagram (labeled V in kN) shows a linear decrease from +75 kN at the left support to -75 kN at the right support, crossing zero at the midpoint (x = 5 m). At the bottom, the bending moment diagram (labeled M in kN·m) is a symmetric parabola peaking at 187.5 kN·m at the center of the span (x = 5 m), indicating maximum moment at midspan." width="332"></p>
</figure>
</div>
<p>The magnitude of the maximum internal bending moment |M<sub>max</sub>| = 187.5 kN·m.</p>
<p>Now determine the required section modulus. Be careful with the order of magnitude of the bending moment and allowable stress.</p>
<p><span class="math display">\[
S_{min}=\frac{187.5\times10^3{~N}\cdot{m}}{12\times10^6\frac{N}{m^2}}=0.015625{~m}^3
\]</span></p>
<p>Use this value to determine the required dimensions of the cross-section. Recall that h = 2b for this beam.</p>
<p><span class="math display">\[
\begin{gathered}
S_{min}=0.015625{~m^3}=\frac{b h^2}{6}=\frac{b(2 b)^2}{6}=\frac{4 b^3}{6}=\frac{2}{3} b^3 \\
b^3=\frac{3}{2} * 0.015625{~m^3}=0.0234375{~m^3} \\
b=~^3\sqrt{0.0234375}=0.286{~m} \\
b=286{~mm} \\
h=2b=2 * 286=572{~mm}
\end{gathered}
\]</span></p>
<p>The minimum required dimensions to ensure this beam doesn’t fail due to bending stress are b = 286 mm and h = 572 mm.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<p>For the purposes of this text it is appropriate to give exact answers to three significant figures. In practice we wouldn’t generally specify the required dimension down to the mm since this is unnecessarily precise to manufacture. It is more practical to design to perhaps the nearest 10 mm, remembering to always round up. For example, we calculated the required dimension b = 153 mm. We must not round this down to 150 mm because this is below the required value, but rounding up to 160 mm would be acceptable. While not included in this problem, a factor of safety (<a href="Chapter 4.html#sec-4.8" class="quarto-xref"><span>Section 4.8</span></a>) is included in all designs in practice.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Step-by-Step: Most Economical Beam Design (rectangular sections)
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Establish the allowable stress, σ<sub>all</sub>, value of sigma for the chosen material by referring to a table of material properties or consulting design specifications. Proceed with the following steps, assuming that σ<sub>all</sub> is the same for tension and compression.</li>
<li>Determine the maximum absolute value of the bending moment |M<sub>max</sub>| in the beam by drawing the shear force and bending moment diagrams (<a href="Chapter 7.html" class="quarto-xref"><span>Chapter 7</span></a> reviews this).</li>
<li>Calculate the minimum allowable value of the section modulus using this equation: <span class="math inline">\(S_{min}=\frac{\left|M_{max}\right|}{\sigma_{allow}}\)</span>.</li>
<li>Set this <span class="math inline">\(S_{\min }=\frac{b h^2}{6}\)</span>, substitute in the given relationship between b and h and solve for the unknown dimension.</li>
</ol>
</div>
</div>
</section></details>
</section>

<section id="sec-9.3" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="sec-9.3"><span class="header-section-number">9.3</span> Unsymmetric Bending—Moment Arbitrarily Applied</h2>
<details>
<summary>
Click to expand
</summary>
<p>Occasionally a member may experience loading where the bending moment, M, doesn’t align with one of the cross-section’s principal axes. In such cases it is advisable to initially resolve the moment into components along the principal axes. The flexure formula can subsequently be applied to ascertain the normal stress induced by each moment component. Finally, employing the principle of superposition helps us determine the resultant normal stress at the specific point.</p>
<div id="fig-9.12" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Decomposition of a moment vector applied to a rectangular cross-section, consisting of three diagrams labeled A and B. In diagram A (on the left), a gray rectangular section is shown with coordinate axes: the y-axis points upward, the z-axis points leftward, and the moment vector M originates at the centroid, inclined at an angle θ from the z-axis toward the y-axis. Diagram A represents the resultant moment vector. Diagrams B (center and right) show the two orthogonal components that add up to form diagram A: the center diagram displays M sub z, a horizontal component directed leftward along the z-axis, and the right diagram shows M sub y, a vertical component directed upward along the y-axis. Together, the two B diagrams vectorially sum to the moment M shown in A, demonstrating that A = B sub 1 + B sub 2." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9.12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/CH9 PNGs/Figure 9.13.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="Decomposition of a moment vector applied to a rectangular cross-section, consisting of three diagrams labeled A and B. In diagram A (on the left), a gray rectangular section is shown with coordinate axes: the y-axis points upward, the z-axis points leftward, and the moment vector M originates at the centroid, inclined at an angle θ from the z-axis toward the y-axis. Diagram A represents the resultant moment vector. Diagrams B (center and right) show the two orthogonal components that add up to form diagram A: the center diagram displays M sub z, a horizontal component directed leftward along the z-axis, and the right diagram shows M sub y, a vertical component directed upward along the y-axis. Together, the two B diagrams vectorially sum to the moment M shown in A, demonstrating that A = B sub 1 + B sub 2." width="524">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9.12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.12: Moment arbitrarily applied to a rectangular cross section
</figcaption>
</figure>
</div>
<p>To systematize this process, envision a beam with a rectangular cross-section subjected to a moment, M, as depicted in <a href="#fig-9.12" class="quarto-xref">Figure&nbsp;<span>9.12</span></a> (A). Here M forms an angle, θ, with the maximum principal z-axis, which is the axis of maximum second moment of area for the cross-section. It is assumed that θ is positive when directed from the positive z-axis toward the positive y-axis. We can resolve M into y and z components.</p>
<p><span class="math display">\[
\begin{aligned}
&amp; M_z=M \cos \theta \\
&amp; M_y=M \sin \theta
\end{aligned}
\]</span></p>
<p><a href="#fig-9.12" class="quarto-xref">Figure&nbsp;<span>9.12</span></a> (B) shows the components of M acting on the rectangular cross section. It’s important to keep track of which side of the beam is in compression and which is tension when subjected to both M<sub>z</sub> and M<sub>y</sub>. Here we’ll use tensile stress as positive and compressive stress as negative. Looking at a +M<sub>z</sub> shows us that this moment causes the top of the section to be in compression and the bottom of the section to be in tension. Inspecting the section when subjected to +M<sub>y</sub> reveals that the left side will be in tension whereas the right side will be in compression. Combining what we know about the sign convention with the flexure formula, we can calculate the resultant normal stress at any point on the cross section by using the following equation:</p>
<p><span id="eq-9.5"><span class="math display">\[
\boxed{\sigma=-\frac{M_z y}{I_z}+\frac{M_y z}{I_y}}\text{ ,}
\tag{9.5}\]</span></span></p>
<div class="line-block">where<br>
<em>𝜎 = Bending stress at point of interest [Pa, psi]</em><br>
<em>M<sub>z</sub>, M<sub>y</sub> = Internal bending moment components about the z-axis and the y-axis [N·m, lb·in.]</em><br>
<em>y, z = Distance in the y and z directions from the centroid to the point of interest [m, in.]</em><br>
<em>I<sub>z</sub>, I<sub>y</sub> = Second moment of area about the centroidal z-axis and y-axis [m<sup>4</sup>, in.<sup>4</sup>]</em></div>
<p>Note that for the signs to work correctly we must assign the appropriate sign to the y and z values and to the components of the bending moment. These values are measured from the coordinate system that originates at the centroid where the x-axis is coming out of the page. It’s also possible to ignore all the signs and use your spatial awareness to determine if each term is in tension or compression due to the applied moment.</p>
<p>Previously we identified the neutral axis—a line marking points of zero stress. When the bending moment acted around the horizontal axis, the neutral axis was also horizontal and passed through the centroid of the cross-section. When the bending moment acts at an angle (θ) from the horizontal axis, the neutral axis will pass through the centroid but will not be horizontal. It too will be at an angle (α).</p>
<p>Let’s now determine the orientation of the neutral axis, as this will commonly not coincide with the axis of bending moment.</p>
<p>Derive the orientation of the neutral axis by setting the previous normal stress equation equal to zero.</p>
<p><span class="math display">\[
0=-\frac{M_z y}{I_z}+\frac{M_y z}{I_y}
\]</span></p>
<p>Then rearrange this to solve for y.</p>
<p><span class="math display">\[
y=\frac{M_y I_z}{M_z I_y} z
\]</span></p>
<p>Now put this equation in terms of M by using <span class="math inline">\(M_z=M \cos \theta\)</span> and <span class="math inline">\(M_y=M \sin \theta\)</span>.</p>
<p><span class="math display">\[
y=\left(\frac{I_z}{I_y} \tan \theta\right) z
\]</span></p>
<p>Since the slope of the line is <span class="math inline">\(\tan \alpha=y / z\)</span>, where the angle α represents the angle the neutral axis forms with the z-axis, this can be written as:</p>
<p><span id="eq-9.6"><span class="math display">\[
\boxed{tan(\alpha)=\left(\frac{I_z}{I_y}tan~\theta\right)}\text{ ,}
\tag{9.6}\]</span></span></p>
<div class="line-block">where<br>
<em>𝛼 = Orientation of the neutral axis, measured from the z-axis [</em><span class="math inline">\(^\circ\)</span><em>,</em> rad<em>]</em><br>
<em>𝜃 = Orientation of the internal bending moment, measured from the z-axis [</em><span class="math inline">\(^\circ\)</span><em>,</em> rad<em>]</em><br>
<em>I<sub>z</sub>, I<sub>y</sub> = Second moment of area about the centroidal z-axis and y-axis [m<sup>4</sup>, in.<sup>4</sup>]</em></div>
<p><a href="#exm-9.5" class="quarto-xref">Example&nbsp;<span>9.5</span></a> and <a href="#exm-9.6" class="quarto-xref">Example&nbsp;<span>9.6</span></a> demonstrate how to calculate bending stress at various points on a cross-section when the moment is arbitrarily applied.</p>
<div id="example-9.5" class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example 9.6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="exm-9.6" class="theorem example">
<p><span class="theorem-title"><strong>Example 9.6</strong></span> &nbsp;</p>
<p>
</p>
<p>A bending moment M = 400 kip⸱in. is applied around an axis 65° above the negative z-axis as shown.</p>
<p>Determine the bending stress at corners A, B, C, and D. Also determine the orientation of the neutral axis with respect to the z-axis.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/chapter 9 figure updates/example 9.6 part 1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A rectangle labeled ABCD is shown with a width of 15 inches along the horizontal z-axis and a height of 8 inches along the vertical y-axis. Dashed green lines represent the y- and z-axes intersecting at the centroid of the rectangle. A diagonal dashed green line extends from the center at a 65° angle above the z-axis, toward the top right. Along this line, a curved blue arrow indicates a clockwise moment labeled M = 400 kip-in. Points A, B, C, and D mark the four corners of the rectangle, each indicated by a black dot." width="404"></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We first determine the components of the bending moment around the y-axis and the z-axis.</p>
<p><span class="math display">\[
\begin{aligned}
&amp; M_y=400 \sin(65^{\circ})=362.5{~kip}\cdot{in.} \\
&amp; M_z=-400 \cos(65^{\circ})=-169.0{~kip}\cdot{in.}
\end{aligned}
\]</span></p>
<p>We’ll also need the second moment of area around both axes.</p>
<p><span class="math display">\[
\begin{gathered}
I_y=\frac{8 * 15^3}{12}=2,250{~in.}^4 \\
I_z=\frac{15 * 8^3}{12}=640{~in.}^4
\end{gathered}
\]</span></p>
<p>Now we can calculate the stress at each corner by using</p>
<p><span class="math display">\[
\sigma=-\frac{M_z y}{I_z}+\frac{M_y z}{I_y}
\]</span></p>
<p>Pay close attention to the signs used for each term.</p>
<p>Corner A:</p>
<p><span class="math display">\[
\sigma_A=-\frac{-169.0{~kip}\cdot{in.} *-4{~in.}}{640{~in.}^4}+\frac{362.5{~kip}\cdot{in.} * 7.5{~in.}}{2,250{~in.}^4}\\ \sigma_A=-1.06{~ksi}+1.21{~ksi}=0.15{~ksi}=0.15{~ksi}~(T)
\]</span></p>
<p>Corner B:</p>
<p><span class="math display">\[
\sigma_B=-\frac{-169.0{~kip}\cdot{in.} * 4{~in.}}{640{~in.}^4}+\frac{362.5{~kip}\cdot{in.} * 7.5{~in.}}{2,250{~in.}^4}\\ \sigma_B=1.05{~ksi}+1.21{~ksi}=2.26{~ksi}=2.26{~ksi }~(T)
\]</span></p>
<p>Corner C:</p>
<p><span class="math display">\[
\sigma_C=-\frac{-169.0{~kip}\cdot{in.} * 4{~in.}}{640{~in.}^4}+\frac{362.5{~kip}\cdot{in.} *-7.5{~in.}}{2,250{~in.}^4}\\ \sigma_C=1.06{~ksi}-1.21{~ksi}=-0.15{~ksi}=0.15{~ksi}~(C)
\]</span></p>
<p>Corner D:</p>
<p><span class="math display">\[
\sigma_D=-\frac{-169.0{~kip}\cdot{in.} *-4{~in.}}{640{~in.^4}}+\frac{362.5{~kip}\cdot{in.} *-7.5{~in.}}{2,250{~in.}^4}\\ \sigma_D=-1.05{~ksi}-1.21{~ksi}=-2.26{~ksi}=2.26{~ksi}~(C)
\]</span></p>
<p>Note that the symmetry of the cross-section causes the stresses at diagonally opposite corners to have the same magnitude but opposite signs. This situation can shorten the problem, enabling us to calculate the stresses at only two corners (say A and B) and identify the stresses at the opposite corners.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/chapter 9 figure updates/example 9.6 part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A rectangle is centered on the coordinate system defined by the vertical y-axis and horizontal z-axis, both represented with dashed lines intersecting at the centroid. A diagonal solid line labeled Neutral axis passes through the rectangle at an upward angle to the right, forming an angle of 31.4° above the z-axis." width="384"></p>
</figure>
</div>
<p>The orientation of the neutral axis is found from</p>
<p><span class="math display">\[
\begin{gathered}
\tan (\alpha)=\frac{I_z}{I_y} \tan (\theta) \\
\alpha=\tan ^{-1}\left(\frac{640{~in.}^4}{2,250{~in.}^4} \tan \left(65^{\circ}\right)\right)=31.4^{\circ}
\end{gathered}
\]</span></p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div id="example-9.6" class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example 9.7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="exm-9.7" class="theorem example">
<p><span class="theorem-title"><strong>Example 9.7</strong></span> &nbsp;</p>
<p>
</p>
<p>A bending moment M = 25 kip⸱ft is applied to a W14 x 43 beam around an axis 40° above the positive z-axis as shown.</p>
<p>Determine the maximum tensile bending stress in the section and the orientation of the neutral axis with respect to the z-axis.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.6 part 1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="An I-shaped cross section is vertically aligned with a dashed vertical y-axis running through its centroid and a horizontal dashed z-axis intersecting it perpendicularly. A dashed moment vector is shown at a 40° angle counterclockwise above the z-axis, labeled M = 25 kip·ft." width="313"></p>
</figure>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The dimensions of the W14 x 43 beam can be found in <a href="Appendix A.html" class="quarto-xref"><span>Appendix A</span></a>. You can also look up the second moment of area about both axes.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.6 part 2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="An I-shaped cross section is shown with key dimensions labeled: an overall height of 13.7 inches, flange thickness of 0.530 inches, flange width of 8 inches, and web thickness of 0.305 inches. A dashed moment vector acts at a 40° angle above the horizontal axis, with the moment labeled M and rotating counterclockwise." width="313"></p>
</figure>
</div>
<p><span class="math display">\[
\begin{gathered}
I_y=45.2{~in}^4 \\
I_z=428{~in}^4
\end{gathered}
\]</span></p>
<p>Next determine the components of the bending moment around the y-axis and the z-axis. Since the bending moment is given in kip⸱ft and all the dimensions are given in inches, convert the bending moment to kip⸱in at this stage.</p>
<p><span class="math display">\[
\begin{aligned}
&amp; M_y=25 \sin \left(40^{\circ}\right) * 12=193{~kip}\cdot{~in.} \\
&amp; M_z=25 \cos \left(40^{\circ}\right) * 12=230{~kip}\cdot{~in.}
\end{aligned}
\]</span></p>
<p>The bending stress at any point can be calculated using</p>
<p><span class="math display">\[
\sigma=-\frac{M_z y}{I_z}+\frac{M_y z}{I_y}
\]</span></p>
<p>The maximum tensile bending stress will occur at the corner where both of these terms are positive. Since both M<sub>z</sub> and M<sub>y</sub> are positive, it should be apparent that the y distance should be negative and the z distance should be positive. Thus the maximum tensile bending stress will occur at the bottom left corner. At this point <span class="math inline">\(y=-\frac{13.7{~in.}}{2}=-6.85{~in.}\)</span> and <span class="math inline">\(z=\frac{8{~in.}}{2}=4{~in}\)</span>.</p>
<p><span class="math display">\[
\sigma=-\frac{230{~kip}\cdot{in.} *-6.85{~in.}}{428{~in.}^4}+\frac{193{~kip}\cdot{in.} * 4{~in.}}{45.2{~in.}^4}=3.68{~ksi}+17.1{~ksi}=20.8{~ksi}~(T)
\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/CH9 PNGs/Example 9.6 part 3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="An I-shaped cross section is shown with vertical dashed line labeled y and a horizontal dashed line labeled z, intersecting at the center of the section. A green diagonal line labeled “Neutral axis” extends from the top left to the bottom right. The angle between the z-axis and the neutral axis is marked as 82.8°." width="304"></p>
</figure>
</div>
<p>The orientation of the neutral axis is found from</p>
<p><span class="math display">\[
\begin{gathered}
\tan (\alpha)=\frac{I_z}{I_y} \tan (\theta) \\
\alpha=\tan ^{-1}\left(\frac{428{~in.}^4}{45.2{~in.}^4} \tan \left(40^{\circ}\right)\right)=82.8^{\circ}
\end{gathered}
\]</span></p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Step-by-Step: Unsymmetric Bending
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Determine the geometric properties of the cross-section, including centroid location and second moment of area (<span class="math inline">\(I_y~\text{and}~I_z\)</span>).</p></li>
<li><p>Determine the point of interest and the distances in the y and z directions from the centroid to this point (<span class="math inline">\(y~\text{and}~z\)</span>).</p></li>
<li><p>Determine the y and z components of the internal bending moment <span class="math inline">\(M_y~\text{and}~M_z\)</span>.</p></li>
<li><p>Calculate the bending stress at the point of interest from <span class="math inline">\(\sigma=-\frac{M_z y}{I_z}+\frac{M_y z}{I_y}\)</span>.</p></li>
</ol>
</div>
</div>
</details>
</section>
<section id="summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<details>
<summary>
Click to expand
</summary>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Key Takeaways
</div>
</div>
<div class="callout-body-container callout-body">
<p>Beams under load experience normal stresses that vary linearly along the height of the cross section. Assuming that the material is homogenous and linear elastic, the flexure formula can be used to calculate the normal stresses. Care must be taken to ensure that bending stresses are reported with magnitude units and tension or compression.</p>
<p>Engineers designing beams must consider how beams respond to bending stress, among other criteria. The design process in this chapter starts with the allowable stress and maximum moment to determine the minimum section modulus. This minimum section modulus is then used to choose an adequate, economical beam shape. (Future chapters present additional criteria for designing a beam.)</p>
<p>When a member experiences loading where the bending moment, M, does not align with one of the cross section’s principal axes, a method of super position is used to determine the resultant normal stress at a specific point. It’s also possible to calculate the orientation of the neutral axis due to this unsymmetric loading.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Key Equations
</div>
</div>
<div class="callout-body-container callout-body">
<p>Flexure formulas: </p>
<p><span class="math display">\[
\begin{gathered}
\sigma_{\max }=\frac{M c}{I} \\
\\
\sigma=\frac{M y}{I}
\end{gathered}
\]</span></p>
<p>Beam design for bending:</p>
<p><span class="math display">\[
S=\frac{I}{c}=\frac{\left|M_{max}\right|}{\sigma_{allow}}
\]</span></p>
<p>Unsymmetric bending—moment arbitrarily applied:</p>
<p><span class="math display">\[
\sigma=-\frac{M_z y}{I_z}+\frac{M_y z}{I_y}
\]</span></p>
<p>Orientation of the neutral axis:</p>
<p><span class="math display">\[
\tan \alpha=\frac{I_z}{I_y} \tan \theta
\]</span></p>
</div>
</div>
</details>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>
<details>
<summary>
Click to expand
</summary>
<p><strong>Figures</strong></p>
<p>All figures in this chapter were created by Kindred Grey in 2025 and released under a CC BY license, except for</p>
<ul>
<li><p>Figure 9.1: Looking up at bridge beams used to support a landscaped bicycle and pedestrian bridge in Seattle. Washington State Dept of Transportation. 2023. CC BY-NC-ND. <a href="https://flic.kr/p/2ojECo3" class="uri">https://flic.kr/p/2ojECo3</a>.</p></li>
<li><p>Figure 9.4: The distortion of a kid’s toy when undergoing bending. Steve Berry. 2006. CC BY-NC-SA. <a href="https://flic.kr/p/4EzyRy" class="uri">https://flic.kr/p/4EzyRy</a>.</p></li>
<li><p>Figure 9.5: Column failure due to bending. Joshua Miller. 2005. CC BY-NC-ND. <a href="https://flic.kr/p/5RLNx" class="uri">https://flic.kr/p/5RLNx</a>.</p></li>
<li><p>Figure 9.9: The end of the prestressed concrete beam showing the prestressing steel and rebar. Mike Sheinin. 2009. All rights reserved. Used under fair use. <a href="https://flic.kr/p/6BW5sA" class="uri">https://flic.kr/p/6BW5sA</a>.</p></li>
</ul>
</details>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Chapter 8.html" class="pagination-link" aria-label="Geometric Properties">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Geometric Properties</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Chapter 10.html" class="pagination-link" aria-label="Shear Loading in Beams">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Shear Loading in Beams</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>